hiero-ledger/solo

README.md

* Adds a standard set of status badges to the `README.md` file.
* An example can be found here: https://github.com/hashgraph/solo/blob/00029-Readme-Status-Badges/README.md
* Closes #29

chore(docs): add status badges to the readme document

---

.github/workflows/zxc-code-analysis.yaml

* set verbose to true for codecov to see what is being uploaded to diagnose missing coverage
* Closes #80

ci: set verbose to true for codecov to see what is being uploaded to diagnose missing coverage

---

README.md
src/core/account_manager.mjs

* updated to allow node client to connect to remote cluster that doesn't have a LoadBalancer
* revert readme --fst-chart-version updates
* Closes #81

fix: updated to allow node client to connect to remote cluster that doesn't have a LoadBalancer

---

src/commands/flags.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/platform_installer.mjs
src/core/templates.mjs
test/e2e/core/platform_installer_e2e.test.mjs
test/unit/core/platform_installer.test.mjs

* fix: fetch platform code directly inside the container
* This is because fetching the platform zip file locally and then uploading to the container is time consuming and brittle.
* feat: allow user to set jvm options for Hedera nodes
When node starts, JVM options are loaded from `/opt/hgcapp/services-Hedera/HapiApp2.0/application.env`
Now user is able to set JVM options with flag `--application-env` flag.  
`node start --application-env application.env`
* Closes #68

feat(cli): allow user to set jvm options for Hedera nodes

---

package-lock.json
package.json
src/commands/account.mjs
src/commands/cluster.mjs
src/commands/flags.mjs
src/commands/index.mjs
src/commands/mirror_node.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/account_manager.mjs
src/core/chart_manager.mjs
src/core/config_manager.mjs
src/core/constants.mjs
src/core/helm.mjs
src/core/k8.mjs
src/core/platform_installer.mjs
test/e2e/commands/01_node.test.mjs
test/e2e/commands/02_account.test.mjs
test/e2e/core/account_manager.test.mjs
test/e2e/core/k8_e2e.test.mjs
test/e2e/core/platform_installer_e2e.test.mjs
test/e2e/setup-e2e.sh
test/test_util.js

* Isolate account initialization and mirror node setup from node command
* Remove unnecessary socket cleanup code (`_stopPortForwards`) as the actual issue was with hedera-sdk-js:
* See: https://github.com/hashgraph/hedera-sdk-js/issues/2194
* Make node-command and account-command e2e tests independent from each other (i.e. use separate namespaces)
* Remove unused function `resetHapiDirectories` to avoid test errors: https://github.com/hashgraph/solo/issues/151
* Closes #143 
* Closes #116 
* Closes #153 
* Closes #165 
* Closes #151 
* https://github.com/hashgraph/solo/issues/168
* https://github.com/hashgraph/solo/issues/169

fix: refactor account initialization and mirror node setup from node command

---

version.mjs

* use FST chart version v0.23.0
* Closes #

fix: use FST chart version v0.23.0

---

test/e2e/core/k8_e2e.test.mjs

This helps to avoid stability in tests
* test: no need to test k8 copy functionality with large build.zip file
This is because `copyTo` and `copyFrom` is a bit buggy for large file: https://github.com/hashgraph/solo/issues/57. Currently it is making our tests unstable as `build.hedera.com` URL is often slow and DDoS measure blocks our curl HEAD requests.
We are currently fetching the build.zip file directly inside the container, so we really don't need to copy a large file to/from a container.
* Closes #

test: no need to test k8 copy functionality with large file

---

src/commands/node.mjs
src/core/account_manager.mjs
src/core/constants.mjs
src/core/k8.mjs
test/e2e/commands/01_node.test.mjs
test/e2e/commands/02_account.test.mjs
test/e2e/core/account_manager.test.mjs
version.mjs

* update HAProxy UP check to use HAProxy Data Plane API
* Closes #169
* Relates to https://github.com/hashgraph/full-stack-testing/pull/809

fix: update HAProxy UP check to use HAProxy Data Plane API

---

.github/workflows/flow-update-readme.yaml
README.md.template

* Auto update example output part of Readme 
* Creating a template file `README.md.template` from existing `README.md`, and  adding some environment variables to replace previous example outputs sections
* Saving command line outputs from solo/kind to environment variables.
* Then using linux utility `envsubst` to replace these pre-defined environment variables in README.md.template
* Only changing README.md if the number of changed lines greater than a certain threshold
* Only trigger trigger the workflow if source code changes
* Closes #121

ci: auto update readme

---

README.md
package.json
src/commands/base.mjs
version.mjs

* fix: return chart-path correctly when chart-directory is specified
* Closes #

fix: return chart-path correctly when chart-directory is specified

---

.github/workflows/flow-update-readme.yaml
README.md
jest.config.mjs
src/commands/node.mjs
src/core/helpers.mjs
src/core/k8.mjs
src/core/platform_installer.mjs
src/core/templates.mjs
src/index.mjs
test/e2e/commands/account.test.mjs
test/e2e/commands/network.test.mjs
test/e2e/commands/node.test.mjs
test/e2e/core/k8_e2e.test.mjs
test/e2e/core/package_downloader_e2e.test.mjs
test/e2e/core/platform_installer_e2e.test.mjs
test/test_util.js
test/unit/commands/base.test.mjs
test/unit/commands/init.test.mjs
test/unit/core/dependency_managers/dependency_manager.test.mjs
test/unit/core/helm.test.mjs
test/unit/core/key_manager.test.mjs
test/unit/core/keytool.test.mjs
test/unit/core/package_downloader.test.mjs
test/unit/core/platform_installer.test.mjs
test/unit/core/zippy.test.mjs

* adds the `solo node refresh` subcommand
* fix `.github/workflows/flow-update-readme.yaml` typo
* add Jest default reporter summary threshold
* added better error handling for `checkNetworkNodeProxyUp`
* enhanced `stopPortForward` to test for port to be closed before continuing
* updated `config.txt` to include fully qualified DNS from Kube DNS
* added dev mode to test loggers for better reporting on failures
* Closes #96 
* Depends on https://github.com/hashgraph/full-stack-testing/pull/815

feat: add node refresh subcommand

---

.gitignore
README.md
package-lock.json
package.json
src/commands/account.mjs
src/commands/flags.mjs
src/core/account_manager.mjs
src/core/k8.mjs
test/e2e/commands/account.test.mjs
test/test_util.js

* add `solo account create --ecdsa-private-key "@@@" --set-alias`
* fix issue where creating Kuberenetes secret was not using base64 encoding
* add `npm run test-coverage` with supporting scripts in `package.json`
* Closes #141

feat: add `solo account create` account alias support

---

src/commands/mirror_node.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/chart_manager.mjs
src/core/k8.mjs
test/e2e/commands/mirror_node.test.mjs
test/e2e/commands/node.test.mjs
test/e2e/commands/relay.test.mjs

* removes 'jest.runAllTicks()' in 1test/e2e/commands/node.test.mjs` as it was causing inconsistent failures
* increased timeout on relay test
* added fst chart version to helm upgrade calls which was missing and causing issues
* Closes #

fix: revert to sleep and remove jest.runAllTicks from e2e test

---

README.md
src/commands/mirror_node.mjs
src/core/k8.mjs
test/data/warmup-cluster.sh
test/e2e/commands/mirror_node.test.mjs
test/e2e/setup-e2e.sh
test/test_util.js
test/unit/core/dependency_managers/dependency_manager.test.mjs
version.mjs

* use a single consensus node during mirror-node-e2e to avoid resource constraints of the runner (4 vCPU, 8 GB RAM)
* I'll need to create a separate PR that updates resource profile to potentially accommodate more nodes in the runner 
* increase timeout for helm dependency check
* use latest FST chart version
* enable warmup-cluster.sh script to pre-load images into the cluster so that actual deployment time is reduced during e2e tests (We shall need to maintain it as we update the chart versions)
* Closes #254

fix: use latest FST chart and a single consensus node during mirror-node e2e test

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-hugo-publish.yaml
.github/workflows/flow-pull-request-checks.yaml
.github/workflows/flow-pull-request-formatting.yaml
.github/workflows/flow-update-readme.yaml
.github/workflows/zxc-code-analysis.yaml
.github/workflows/zxc-compile-code.yaml

* bump e2e tests to use solo linux large
* auto retry setup-node action
* update workflow concurrency groups to be more unique
* Closes #

ci: bump to solo linux large and auto retry setup node

---

src/core/k8.mjs

* Apparently JSDoc could not parse "Promise<[*]>" 
* Closes #268

fix: jsdoc could not recognizing Promise<[*]>

---

.github/workflows/flow-pull-request-checks.yaml
.github/workflows/flow-pull-request-formatting.yaml

* the concurrency group change did not work as intended, reverting to prior changes
* Closes #

ci: revert concurrency group change

---

src/core/k8.mjs
test/e2e/commands/node.test.mjs

* increase wait time for when recycling an haproxy pod for a node that causes e2e node.test.mjs to fail and timeout when many runners are active in CI pipeline
> example failure: https://github.com/hashgraph/solo/actions/runs/9035734886/job/24831179235?pr=284
* Closes #291

fix: increase wait time for when recycling an haproxy pod for a node

---

.github/workflows/zxc-e2e-test.yaml

* add use of cgroups into `.github/workflows/zxc-e2e-test.yaml` to ensure that runner retains enough resources to stay connected to GitHub and not get canclled
* Closes #293

ci: use cgroups in github agent runner

---

src/commands/network.mjs
src/commands/node.mjs
src/commands/relay.mjs
src/core/constants.mjs
src/core/k8.mjs
test/e2e/core/k8_e2e.test.mjs
test/unit/core/k8.test.mjs

* refactored K8 waitForPod
* handle a predicate function
* renamed to waitForPods
* take an array of phases
* refactored K8 waitForPodCondition
* renamed to waitForPodConditions
* removed promise/delay/retry loop and instead call waitForPods with predicate to check conditions
* added `test/unit/core/k8.test.mjs` for some negative tests
* Closes #315

fix: refactor waitForPod and waitForPodConditions to stabilize code timeouts during e2e tests

---

.github/workflows/flow-hugo-publish.yaml

* /.github/workflows/flow-hugo-publish.yml to pin commits to actions in the workflow
* Closes #324

ci: Updated workflows to pin commits to actions

---

.gitignore
package.json
resources/templates/log4j2.xml
src/commands/flags.mjs
src/commands/mirror_node.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/account_manager.mjs
src/core/config_manager.mjs
src/core/constants.mjs
src/core/k8.mjs
src/core/network_node_services.mjs
src/core/platform_installer.mjs
src/core/templates.mjs
src/index.mjs
test/e2e/commands/account.test.mjs
test/e2e/commands/cluster.test.mjs
test/e2e/commands/mirror_node.test.mjs
test/e2e/commands/network.test.mjs
test/e2e/commands/node-local-hedera.test.mjs
test/e2e/commands/node-local-ptt.test.mjs
test/e2e/commands/relay.test.mjs
test/e2e/core/k8_e2e.test.mjs
test/e2e/core/platform_installer_e2e.test.mjs
test/e2e/e2e_node_util.js
test/e2e/setup-e2e.sh
test/test_util.js
test/unit/core/k8.test.mjs
test/unit/core/platform_installer.test.mjs
version.mjs

* use `Running` phase for proxy check during `solo network deploy`
* remove haproxy recycle pod logic, instead use waitForPodReady which uses the PodCondition[Ready] = true that the haproxy is now setting based on the startupProbe
* removed checkNetworkNodeProxyUp
* use in test cases HEDERA_PLATFORM_VERSION = 'v0.49.0-alpha.2' since this is the first version to support FQDN correctly
* enhanced prepareAddressBookBase64 to convert FQDN to IP addresses to support Mirror Node
* enhanced nodeClient creation to set more robust timeouts and backoffs
* refactored getNodeServiceMap() to use a new class NetworkNodeServices to strongly type variables and give it more attributes that can be provide more reuse
* updated prepareConfigTxt() to use accountId from …

fix: updates to accommodate haproxy changes in FST charts

---

src/commands/init.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/platform_installer.mjs
src/core/profile_manager.mjs
test/e2e/commands/network.test.mjs
test/unit/core/profile_manager.test.mjs

* mount `/etc/network-node/application.env` as a configMap to the network nodes
* Closes #110

feat: mount application.env as a configMap

---

.github/workflows/zxc-e2e-test.yaml
src/commands/node.mjs
src/core/helpers.mjs
test/e2e/commands/account.test.mjs
test/e2e/commands/cluster.test.mjs
test/e2e/commands/mirror_node.test.mjs
test/e2e/commands/network.test.mjs
test/e2e/commands/node-local-hedera.test.mjs
test/e2e/commands/node-local-ptt.test.mjs
test/e2e/commands/relay.test.mjs
test/e2e/e2e_node_util.js

* Add help function to download swirlds.log and hgcaa.log
* Add logs command so we can use `solo node logs` to download logs to ~/.solo directory
* Closes #336

feat: add node logs command

---

version.mjs

* Updates default Full Stack helm chart version.
* Closes #361

fix: update default full stack chart version

---

.github/workflows/flow-build-application.yaml
.github/workflows/flow-pull-request-checks.yaml

* update `flow-pull-request-checks.yaml` and `flow-build-application.yaml`
* make `e2e-mirror-node-tests` run after `e2e-tests`
* make `e2e-relay-tests` run after `e2e-mirror-node-tests`
* Closes #366

ci: reduce number of e2e running concurrently but without increasing total time for PR checks

---

test/data/local-ptt-app-values.yaml
test/e2e/commands/node-local-ptt.test.mjs
version.mjs

* Updates the default helm chart version.
* Closes #377

fix: update default helm chart version

---

version.mjs

Increases the version of the full-stack-testing charts to `v0.29.0`
* Closes #

chore: bump fst chart version to 0.29.0

---

src/commands/cluster.mjs
src/commands/flags.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/account_manager.mjs
src/core/constants.mjs
src/core/helpers.mjs
src/core/k8.mjs
src/core/logging.mjs
src/core/platform_installer.mjs
src/core/templates.mjs
test/unit/core/profile_manager.test.mjs

* use path.join instead of forward slashes to support Windows
* Closes #490

fix: use path.join instead of forward slashes to support Windows

---

src/commands/flags.mjs
src/commands/node.mjs
src/commands/prompts.mjs
test/e2e/commands/node-add.test.mjs

* reset the disablePrompt attribute for the definition under each flag
* add local build path to the disabled prompts for node add
* Closes #514

fix: node add call triggers no prompt found for local-build-path error and exits

---

package-lock.json
package.json
src/core/account_manager.mjs

* removed the custom ip address logic and '@hashgraph/proto' 
* Closes #493

fix: removed the custom ip address logic and '@hashgraph/proto'

---

.github/workflows/flow-build-application.yaml
.github/workflows/flow-pull-request-checks.yaml
src/commands/network.mjs
src/commands/node.mjs
src/core/k8.mjs
src/core/key_manager.mjs
src/core/platform_installer.mjs
src/core/templates.mjs
test/e2e/core/account_manager.test.mjs
test/e2e/core/k8_e2e.test.mjs
test/e2e/core/platform_installer_e2e.test.mjs
test/test_util.js
test/unit/core/platform_installer.test.mjs
version.mjs

* use k8s secrets to store node gossip and grpc tls keys and mount them
* Closes #135

feat: use k8s secrets to store node gossip and grpc tls keys and mount them

---

src/commands/mirror_node.mjs
src/commands/network.mjs
src/commands/node.mjs
src/core/account_manager.mjs
src/core/k8.mjs
src/core/key_manager.mjs
src/core/platform_installer.mjs
test/e2e/commands/network.test.mjs
test/e2e/commands/node-delete.test.mjs
test/e2e/core/chart_manager.test.mjs
test/e2e/core/k8_e2e.test.mjs
test/testSequencer.mjs

* Fix test cases hanging due to missing await keywords, this could have been causing a lot of our pipeline issues
* during `solo node update` check for pod to be condition ready to make sure that sidecars are up
* fix random test sequence to give the same sequence consistently provided the same seed is used
* make sure that the node client is closed first in refreshNodeClient
* change the remaining two references of 'sh' to 'bash'
* fixed some issues causing random test failures
* Closes #550

fix: added missing async/await where needed

---

package-lock.json
package.json
src/commands/index.mjs
src/commands/init.mjs
src/commands/node.mjs
src/commands/relay.mjs
src/core/constants.mjs
src/core/dependency_managers/dependency_manager.mjs
src/core/k8.mjs
src/core/platform_installer.mjs

Fixed some jsdoc errors because it did not support some auto generated mjs documentation styles.
Also run jsdoc when doing syntax format check so we do not need separate jsdoc check from ci flow as mentioned in #544
* Closes #543
* Closes #544

fix: jsdoc errors due to unrecognized format

---

src/core/k8.mjs

Removed the 'z' from the 'tar' command on the K8.copyFrom method in order to disable the compression
* Closes # [57](https://github.com/hashgraph/solo/issues/57)

fix(functionality): removed the 'z' from the 'tar' command on the K8.copyFrom

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-update-readme.yaml
README.md.template

* have update readme run after version calculation in deploy and release
* update readme template for current version changes

fix: have update readme run after version calculation in deploy and release

---

.github/workflows/flow-update-readme.yaml

* update readme workflow to use boolean instead of string
* Closes #593

fix: update readme workflow to use boolean instead of string

---

src/commands/node.mjs

*  check if data/upgrade/data/keys exisit
* Closes #541

fix: check if data/upgrade/data/keys exisit

---

.github/workflows/flow-deploy-release-artifact.yaml

* update readme workflow to use version from semantic-release
* Closes #593

fix: update readme workflow to use version from semantic-release

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-update-readme.yaml

* more update readme testing
* Closes #594

fix: more update readme testing

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-update-readme.yaml

* deploy and tag uses commit-hash from readme
* Closes #594

fix: deploy and tag uses commit-hash from readme

---

src/commands/mirror_node.mjs
src/commands/network.mjs
src/commands/relay.mjs

Ensured user-provided values file takes precedence over solo-generated values
* Closes # [496](https://github.com/hashgraph/solo/issues/496)

feat: ensured user-provided values file takes precedence over solo-generated values

---

src/commands/account.mjs
src/commands/cluster.mjs
src/commands/init.mjs
src/commands/mirror_node.mjs
src/commands/network.mjs
src/commands/node.mjs
src/commands/prompts.mjs
src/commands/relay.mjs
src/core/account_manager.mjs
src/core/chart_manager.mjs
src/core/config_manager.mjs
src/core/dependency_managers/dependency_manager.mjs
src/core/dependency_managers/keytool_dependency_manager.mjs
src/core/errors.mjs
src/core/helpers.mjs
src/core/k8.mjs
src/core/key_manager.mjs
src/core/package_downloader.mjs
src/core/platform_installer.mjs
src/core/profile_manager.mjs
src/core/templates.mjs
src/core/zippy.mjs
test/e2e/core/k8_e2e.test.mjs
test/unit/core/dependency_managers/dependency_manager.test.mjs
test/unit/core/errors.test.mjs
test/unit/core/zippy.test.mjs

* rename to SoloError
* Closes #610

chore: rename to SoloError

---

package.json

* fixing jsdoc failed but ci job not failed
* Closes #607
---
Now ci job would fail if jsdoc reported errors
https://github.com/hashgraph/solo/actions/runs/10924368487/job/30323236542

fix: jsdoc failed but ci job not failed

---

README.md.template

* update readme with port forward example
* Closes #516

chore: update readme with port forward example

---

src/commands/flags.mjs
src/commands/mirror_node.mjs
src/commands/prompts.mjs
src/core/chart_manager.mjs
test/e2e/commands/mirror_node.test.mjs

Add new optional '--mirror-node-version' flag to override default mirror node version. It can be supplied on the 'solo mirror-node deploy' command and changes the image tag.
* Closes # [495](https://github.com/hashgraph/solo/issues/495)

feat: Add '--mirror-node-version' flag to override default mirror node version

---

test/test_util.js
test/unit/commands/base.test.mjs
test/unit/commands/init.test.mjs
test/unit/core/platform_installer.test.mjs

Start Kind cluster on demand if not having a kube config errors
* Closes # [359](https://github.com/hashgraph/solo/issues/359)
This pull request might also render [issue #360](https://github.com/hashgraph/solo/issues/360) obsolete

fix(tests): start Kind cluster on demand if not having a kube config errors

---

src/commands/node.mjs

Fixes the way flags are being passed in the declaration of the `solo node start` and `solo node stop` commands.
* Closes #635

fix: Direct calling of node stop and start commands

---

test/scripts/README.md

* updated README with an example to use openssl to generate node keys (gossip keys and gRPC TLS keys)
* Closes #

docs: update README with node key generation example

---

.github/workflows/flow-hugo-publish.yaml

* Fix step names
* Closes #668

ci: fix formatting

---

resources/support-zip.sh

* increase stability in resources/support-zip.sh
* Closes #680

fix: increase stability in resources/support-zip.sh

---

resources/extract-platform.sh

* increase stability in resources/extract-platform.sh
* Closes #679

fix: increase stability in resources/extract-platform.sh

---

.github/workflows/flow-deploy-release-artifact.yaml

* update our release artifact build process to generate the dist folder for our TypeScript compiled JS files
* Closes #702

ci: update our release artifact build process to generate the dist folder for our TypeScript compiled JS files

---

package.json
resources/post-build-script.js
src/core/constants.ts
src/core/helpers.ts

* fix missing file issues when running solo from npm install -g
* Closes #702

fix: fix missing file issues when running solo from npm install -g

---

package.json
resources/post-build-script.js
src/core/helpers.ts

* fix incorrect loading of package.json
* Closes #702

fix: fix incorrect loading of package.json

---

src/index.ts

* Check namespace before logging 
* Closes #721 
Output result
```
******************************* Solo *********************************************
Version			: 0.31.1
Kubernetes Context	: kind-solo-e2e
Kubernetes Cluster	: kind-solo-e2e
**********************************************************************************
✔ Setup home directory and cache
✔ Check dependencies
```

fix: undefined log output of namespace

---

test/unit/core/dependency_managers/dependency_manager.test.ts

Remove test since it was causing timeout's and is already covered in other tests
Test:
* DependencyManager
* checkDependency
* should succeed during helm dependency check
* Closes # [#783](https://github.com/hashgraph/solo/issues/783)

test: remove test that is causing timeouts

---

src/commands/network.ts
src/core/chart_manager.ts

* added logic to check if cluster setup chart installed or not before network deploy
* Closes #782
Test output
```
✔ Initialize
✔ Acquire lease - namespace not created, skipping lease acquire
✔ Generate gossip keys [0.4s]
✔ Backup old files
✔ Gossip key for node: node1 [0.4s]
✔ Generate gRPC TLS Keys [0.8s]
✔ Backup old files
✔ TLS key for node: node1 [0.7s]
✔ Finalize
✔ generate key files (1329ms)
✔ Initialize
✔ Acquire lease - lease acquired successfully, attempt: 1/10
✖ Chart solo-cluster-setup is not installed. Run 'solo cluster setup'
◼ Prepare staging directory
◼ Copy node keys to secrets
◼ Install chart 'solo-deployment'
◼ Check node pods are running
◼ Check proxy pods are running
◼ Check auxiliary pods are ready
```

fix: check if setup chart installed or not before network deploy

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-hugo-publish.yaml
.github/workflows/templates/template.zxc-code-analysis.yaml
.github/workflows/zxc-code-analysis.yaml
.github/workflows/zxc-code-style.yaml
.github/workflows/zxc-e2e-test.yaml
.github/workflows/zxc-unit-test.yaml
.github/workflows/zxc-update-readme.yaml
.gitignore
package-lock.json
src/commands/account.ts
src/core/k8.ts
src/index.ts

* use nodejs cached version to avoid downloading issues
* add a couple of account creates after account init to trigger the handler
* update version check to work in case no cluster is found
* Closes #

ci: use nodejs cached version to avoid downloading issues

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-hugo-publish.yaml
.github/workflows/flow-task-test.yaml
.github/workflows/templates/template.zxc-code-analysis.yaml
.github/workflows/zxc-code-analysis.yaml
.github/workflows/zxc-code-style.yaml
.github/workflows/zxc-e2e-test.yaml
.github/workflows/zxc-unit-test.yaml
.github/workflows/zxc-update-readme.yaml
package-lock.json
package.json

* only set major version for NodeJS to leverage the version cached on the runner which can change
* Closes #

chore(ci): only set major version for NodeJS to leverage the version cached on the runner which can change

---

src/commands/node/configs.ts
src/commands/node/flags.ts
src/core/constants.ts
src/core/helpers.ts
test/test_util.ts

* Fixed unparsed node alias node assigned error
* Fixed the incorrect log download source directory
* Added a unit check to check if download is working
* Closes #847

fix: flag check of node logs command and incorrect download source

---

.github/workflows/flow-hugo-publish.yaml

Change peaceiris/actions-hugo action to a step-security maintained version
* Closes #887

ci: Change peaceiris/actions-hugo action to a step-security maintained version

---

examples/custom-network-config/Taskfile.yml
examples/custom-network-config/init-containers-values.yaml

* Fixed the example task file incorrect path to helper file and node id still starts from 0
* Closes #878
To test the custom Taskfile, run the following command
```bash
task helper:cluster:create
task helper:cluster:setup
cd examples/custom-network-config
task default 
task show:ips
task clean
```

fix: node id should start from `1`

---

eslint.config.mjs
src/commands/account.ts
src/commands/cluster.ts
src/commands/deployment.ts
src/commands/flags.ts
src/commands/mirror_node.ts
src/commands/network.ts
src/commands/node/tasks.ts
src/commands/relay.ts
src/core/config/local_config.ts
src/core/config/remote/remote_config_tasks.ts
src/core/k8.ts
src/core/task.ts
src/types/index.ts
test/unit/commands/context.test.ts

* add eslint config @typescript-eslint/consistent-type-imports to reduce chances of circular dependencies
* Relates to #928

chore: add eslint config @typescript-eslint/consistent-type-imports

---

DEV.md
README.md
Taskfile.yml
docs/content/User/Env.md
docs/content/User/FAQ.md
docs/content/User/GetStarted.md
docs/content/User/SoloWithMirrorNode.md
docs/content/User/TaskTool.md
docs/data/menu/main.yml

* Add section for using environment variables and FAQ
* Update Dev.md
#914

feat: Update document

---

docs/content/User/SoloWithMirrorNode.md
docs/content/User/TaskTool.md

* Fix some typos in documentation

fix: document typo

---

README.md

* Update README that v0.32.0+ only supports hedera v0.58.1+
* update readme about breaking changes in v0.32.0 instead of v1.0.0
* Closes #1041

chore: update README that v0.32.0+ only supports hedera v0.58.1+

---

.releaserc

* update release rc to treat breaking changes for minor version bump instead of major
* Closes #1035

ci: update release rc to treat breaking changes for minor version bump instead of major

---

src/commands/mirror_node.ts
test/e2e/commands/mirror_node.test.ts

Added new step to the deploy process for the mirror node to upgrade the solo-charts with the appropriate values.
* Closes [#58](https://github.com/hashgraph/solo-charts/issues/58)

feat: Updating solo to leverage changes after moving acme-cluster-issuer and haproxy-ingress out of mirror-node-explorer

---

docs/content/User/SDK.md

- Replaced `task default-with-mirror-node` to `task default-with-mirror` Since the `task default-with-mirror-node` does not work anymore and also to ensure synchronicity with [Use the Task tool to launch Solo](https://github.com/hashgraph/solo/blob/main/docs/content/User/TaskTool.md ).
- Fixed typos for `OPERATOR_ID` and `OPERATOR_KEY` to remove incorrect escape character.

docs(SDK): Fix incorrect command and fix typos

---

src/commands/deployment.ts
src/core/config/local_config.ts

* made localconfig set the user email address if's already present.
* removed flags from execute prompt inside `deployment create` that prevent getting the existing email address from localconfig.
* Closes [#975](https://github.com/hashgraph/solo/issues/975)

fix: solo deployment create should use email address in local config if it is already there instead of prompting the user for it

---

README.md
docs/content/User/SDK.md
docs/layouts/_default/_markup/render-link.html

* Fixed the default html link hood rendering template, it was incorrectly replacing external link to empty string
* Closes #1114

fix: external link rendering

---

.github/workflows/flow-task-test.yaml
Taskfile.helper.yml
Taskfile.yml
examples/Taskfile.examples.yml

* should run npm install before build
* Closes #1116

fix: should run `npm install` before build

---

src/commands/base.ts
src/commands/cluster/handlers.ts
src/commands/cluster/tasks.ts
src/commands/init.ts

Adds a new task to `solo cluster connect` for creating all home directories in case any of them are missing.
* Closes #1121

fix: Bug when running `solo cluster connect` after fresh install

---

src/core/helpers.ts

* fix file size empty error when throttle file is provided on command line
* Closes #1139

fix: file size empty error when throttle file is provided on command line

---

src/commands/network.ts
src/core/config/local_config.ts
src/core/config/remote/remote_config_manager.ts

When `network destroy` is called and the namespace will be emptied but not deleted, remote config's components data will be emptied. 
* Closes [#965](https://github.com/hashgraph/solo/issues/965)

feat: solo network destroy should update remote-config

---

.github/workflows/flow-task-test.yaml
.github/workflows/zxc-e2e-test.yaml
Taskfile.helper.yml
examples/performance-tuning/latitude/Taskfile.yml
examples/performance-tuning/latitude/application.properties
resources/templates/application.properties
src/commands/flags.ts
src/commands/node/tasks.ts
src/core/platform_installer.ts
src/core/profile_manager.ts
test/e2e/commands/node_local_hedera.test.ts
test/e2e/commands/node_local_ptt.test.ts
test/test_add.ts
test/unit/core/profile_manager.test.ts
version.ts

if the Hedera platform version satisfied 0.59.x or is greater set the internal IP address to 127.0.0.1 in config.txt 
else use the existing logic 
* Closes [#1150](https://github.com/hashgraph/solo/issues/1150)

feat: for v0.59.x or greater set the internal IP address to 127.0.0.1 to avoid an ISS, in config.txt

---

src/commands/mirror_node.ts
src/commands/network.ts
src/commands/node/handlers.ts
src/commands/relay.ts
src/core/config/remote/remote_config_manager.ts
src/index.ts

- Removes all usages of `RemoteConfigTasks.loadRemoteConfig.bind(this)(argv),`
- Adds a new middleware that loads the remote config before the commands are executed. This is skipped for several commands:
`init`, `node keys`, `cluster info`, `cluster list` - They do not require connecting to a remote cluster.
`deployment create`, `cluster connect` - Require connecting to several clusters and that is handled by the command task logic.
* Closes #1171

feat: Update solo to load remote config near entry point

---

src/commands/cluster/tasks.ts
src/core/config/local_config.ts
src/core/config/remote/remote_config_manager.ts
src/core/k8.ts
src/index.ts
test/unit/commands/cluster.test.ts

- Removes the public method `getKubeConfig` in `K8`
- Adds new methods for accessing context and cluster data: `getCurrentContext`, `getCurrentContextObject`, `getCurrentCluster`, `getCurrentClusterName`
* Closes #1179

fix: remove k8.getKubeConfig

---

.github/workflows/flow-task-test.yaml
Taskfile.helper.yml
src/commands/explorer.ts
src/commands/flags.ts
src/commands/index.ts
src/commands/mirror_node.ts
src/core/constants.ts
src/core/k8.ts
test/e2e/commands/mirror_node.test.ts

* Create new command for explorer deploy and destroy
* Update k8 waitingForPod with extra `namespace` parameter
* Update mirror node e2e test 
* Closes #1081

feat: separate explorer from mirror node install/uninstall

---

src/commands/flags.ts
src/commands/node/configs.ts
src/commands/node/flags.ts
src/commands/node/handlers.ts
src/commands/node/tasks.ts
src/core/genesis_network_models/genesis_network_data_constructor.ts
test/test_util.ts

feat: Add adminKey flag to node setup command

---

src/commands/cluster/tasks.ts
src/core/config/local_config.ts
src/core/k8.ts
src/core/kube/t_directory_data.ts
src/index.ts
test/e2e/e2e_node_util.ts
test/e2e/integration/core/k8_e2e.test.ts
test/unit/commands/cluster.test.ts

* made getContexts() private and instead have classes use getContextNames()
* moved interface TDirectoryData into its own file
* removed unused method getClusterIP()
* made methods in K8 that were only used in K8 private
* added public modifier to public methods in K8
* Relates to #1039

refactor: minor refactors to K8 setting private and public modifiers

---

src/commands/mirror_node.ts
src/commands/node/configs.ts
src/commands/node/helper.ts
src/commands/node/node_add_config.ts
src/commands/node/tasks.ts
src/core/account_manager.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
src/core/kube/kube_errors.ts
src/core/kube/pod_ref.ts
src/core/platform_installer.ts
test/e2e/commands/mirror_node.test.ts
test/e2e/commands/network.test.ts
test/e2e/commands/node_delete.test.ts
test/e2e/commands/node_update.test.ts
test/e2e/commands/node_upgrade.test.ts
test/e2e/commands/separate_node_add.test.ts
test/e2e/commands/separate_node_delete.test.ts
test/e2e/commands/separate_node_update.test.ts
test/e2e/commands/separate_node_upgrade.test.ts
test/e2e/e2e_node_util.ts
test/e2e/integration/core/account_manager.test.ts
test/e2e/integration/core/k8_e2e.test.ts
test/e2e/integration/core/platform_installer_e2e.test.ts
test/test_add.ts
test/test_util.ts
test/unit/core/platform_installer.test.ts

* created PodRef class
* use PodRef class across codebase
* Closes #1253

refactor: add k8.PodRef class and implement it across the codebase

---

src/core/config/remote/remote_config_manager.ts
src/core/kube/config_maps.ts
src/core/kube/container_name.ts
src/core/kube/errors/kube_api_error.ts
src/core/kube/errors/namespace_name_invalid_error.ts
src/core/kube/errors/resource_operation_errors.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
src/core/kube/k8_client/k8_client_config_maps.ts
src/core/kube/kube_api_response.ts
src/core/kube/kube_validation.ts
src/core/kube/namespace_name.ts
src/core/kube/pod_name.ts
src/core/kube/pod_ref.ts
src/core/kube/resource_operation.ts
src/core/kube/resource_type.ts
test/e2e/commands/cluster.test.ts
test/unit/core/kube/namespace_name.test.ts

* Adds an implementation of the `ConfigMaps` fluent interface
* Closes #1242

feat: add configmaps fluent interface implementation

---

src/core/kube/container.ts
src/core/kube/containers.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
src/core/kube/k8_client/k8_client_container.ts
src/core/kube/k8_client/k8_client_containers.ts
src/core/kube/pod.ts

* create k8.Container interface
* move container methods from Pod to Container
* implement K8ClientContainer and implement across codebase)
* Closes #1257 
* Closes #1256 
* Closes #1258

refactor: create k8.Container interface, move container methods from Pod to Container, implement K8ClientContainer and implement across codebase

---

src/core/kube/contexts.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
src/core/kube/k8_client/k8_client_clusters.ts
src/core/kube/k8_client/k8_client_config_maps.ts
src/core/kube/k8_client/k8_client_container.ts
src/core/kube/k8_client/k8_client_containers.ts
src/core/kube/k8_client/k8_client_contexts.ts

* Adds the `K8ClientContexts` implementation for the `Contexts` fluent interface
* Closes #1243

feat: add contexts fluent interface implementation

---

src/commands/cluster/tasks.ts
src/commands/deployment.ts
src/commands/explorer.ts
src/core/cluster_checks.ts
src/core/container_init.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
test/unit/commands/cluster.test.ts
test/unit/commands/network.test.ts

* created ClusterChecks and pulled cluster check methods from K8
* Closes #1265

refactor: created ClusterChecks and pulled cluster check methods from K8

---

src/commands/node/tasks.ts
src/core/kube/container_name.ts
src/core/kube/container_ref.ts
src/core/kube/errors/invalid_resource_name_error.ts
src/core/kube/errors/missing_namespace_error.ts
src/core/kube/errors/missing_parent_resource_error.ts
src/core/kube/errors/missing_resource_name_error.ts
src/core/kube/errors/namespace_name_invalid_error.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
src/core/kube/k8_client/k8_client_config_maps.ts
src/core/kube/k8_client/k8_client_container.ts
src/core/kube/k8_client/k8_client_pod.ts
src/core/kube/k8_client/k8_client_pods.ts
src/core/kube/k8_client/k8_client_secrets.ts
src/core/kube/kube_api_response.ts
src/core/kube/nested_resource_ref.ts
src/core/kube/pod_name.ts
src/core/kube/pod_ref.ts
src/core/kube/resource_name.ts
src/core/kube/resource_ref.ts
src/core/kube/resource_type.ts
src/core/kube/secrets.ts
src/core/network_nodes.ts
src/core/platform_installer.ts
test/e2e/e2e_node_util.ts
test/e2e/integration/core/k8_e2e.test.ts

* Adds `K8ClientSecrets` class which implements the `Secrets` interface
* Refactors and reduces code duplication across `PodName`, `PodRef`, `ContainerRef`, and `ContainerName` classes
* Misc refactors or enhancements
* Closes #1245

feat: add secrets fluent interface implementation

---

src/core/cluster_checks.ts
src/core/kube/config_maps.ts
src/core/kube/k8_client.ts
src/core/kube/k8_client/k8_client_config_maps.ts
src/core/kube/k8_client/k8_client_pod.ts
src/core/kube/k8_client/k8_client_pods.ts
src/core/kube/pods.ts
test/e2e/integration/core/k8_e2e.test.ts
test/e2e/integration/core/remote_config_validator.test.ts

* add ConfigMaps.list()+listForAllNamespaces()
* rename of k8 client fluent methods to conform to pattern
* add Pods.create()
* Closes #1259
* Closes #1264
* Closes #1311

refactor: add ConfigMaps.list()+listForAllNamespaces(), Pods.create(), and rename of k8 client fluent methods to conform to pattern

---

src/core/account_manager.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts

* Removes the legacy `*Svcs*` methods and replaces their usages with the new fluent `services()` methods.
* Closes #1270

refactor: remove legacy k8 services methods

---

src/commands/account.ts
src/commands/mirror_node.ts
src/commands/network.ts
src/commands/relay.ts
src/core/account_manager.ts
src/core/certificate_manager.ts
src/core/kube/k8.ts
src/core/kube/k8_client.ts
src/core/kube/k8_client/k8_client_secrets.ts
src/core/kube/secret_type.ts
src/core/kube/secrets.ts
src/core/platform_installer.ts
test/e2e/commands/network.test.ts
test/unit/core/certificate_manager.test.ts

* Replaces all legacy `*Secret*` method usages with the new fluent interface via the `secrets()` API
* Closes #1271

refactor: remove legacy k8 secret methods

---

src/commands/mirror_node.ts
src/commands/network.ts
src/core/kube/k8.ts
src/core/kube/k8_client/k8_client.ts
src/core/kube/resources/pvc/pvcs.ts
test/e2e/commands/network.test.ts

…f the fluent pattern
* update codebase to use k8.pvcs methods directly
* Closes #1272

refactor: update codebase to use k8.pvcs methods directly

---

src/commands/deployment.ts
src/commands/network.ts
src/commands/node/handlers.ts
src/core/config/local_config_data.ts
src/core/config/remote/cluster.ts
src/core/config/remote/components/base_component.ts
src/core/config/remote/components/consensus_node_component.ts
src/core/config/remote/enumerations.ts
src/core/config/remote/listr_config_tasks.ts
src/core/config/remote/remote_config_data.ts
src/core/config/remote/remote_config_data_wrapper.ts
src/core/config/remote/remote_config_manager.ts
src/core/config/remote/types.ts
test/e2e/integration/core/remote_config_validator.test.ts
test/unit/core/config/remote/cluster.test.ts
test/unit/core/config/remote/components/components.test.ts
test/unit/core/config/remote/components_data_wrapper.test.ts
test/unit/core/config/remote/metadata.test.ts
test/unit/core/config/remote/migration.test.ts
test/unit/core/config/remote/remote_config_data_wrapper.test.ts

* add support for new data types `ClusterRef` and `Cluster`
* update RemoteConfig to handle multi-cluster networking
* fix typo: `replays` -> `relays`
* Closes #1345

fix: update RemoteConfig to handle multi-cluster networking

---

Taskfile.helper.yml
examples/external-database-test/Taskfile.yml
examples/external-database-test/scripts/init.sh
src/commands/flags.ts
src/commands/mirror_node.ts
test/e2e/commands/mirror_node.test.ts

Added the ability to provide a readonly user name and password for the external database. 
New flags:
* `--external-database-read-username` - PostgreSQL readonly user's username.
* `--external-database-read-password` - PostgreSQL readonly user's password.
the owner is set as the owner inside the mirror-node helm chart and the mirror node importer,
all of the other services use the readonly user - gRPC, restJava, web3, rest...
* Closes [#1349](https://github.com/hashgraph/solo/issues/1349)

feat(external-database): add ability to pass readonly user to the external database

---

src/commands/cluster/configs.ts
src/commands/cluster/tasks.ts
src/commands/deployment.ts
src/core/config/local_config.ts
src/core/config/local_config_data.ts
src/core/config/remote/listr_config_tasks.ts
src/core/config/remote/remote_config_manager.ts
src/core/error_messages.ts
src/core/validator_decorators.ts
test/data/local-config.yaml
test/e2e/integration/core/remote_config_manager.test.ts
test/test_container.ts
test/test_util.ts
test/unit/commands/cluster.test.ts
test/unit/commands/network.test.ts
test/unit/core/local_config.test.ts

- Removes the `currentDeploymentName` from `LocalConfig`
- Renames `clusterContextMapping` to `clusterRefs`
* Closes #1346

refactor: Update LocalConfig to support multiple clusters based on the new design

---

.github/workflows/flow-build-application.yaml
.github/workflows/flow-pull-request-checks.yaml

* set unique e2e job names to prevent failure
* set e2e parallel jobs to 5
* Closes #

ci: set unique e2e job names to prevent failure and set e2e parallel jobs to 5

---

src/commands/base.ts
src/commands/flags.ts
src/commands/network.ts
src/core/config/local_config.ts
src/core/config/local_config_data.ts
src/core/config/remote/types.ts
test/unit/commands/network.test.ts

* add support for multi-cluster values files
* create secrets in multiple clusters
* create namespace in multiple clusters as required
* add a custom flag called `networkDeploymentValuesFile` to be used for `solo network deployment` command
* Related #1357

feat: handle multiple contexts during network deploy

---

.github/workflows/flow-pull-request-checks.yaml
.github/workflows/zxc-unit-test.yaml
src/commands/network.ts
version.ts

* Updates the Solo helm chart version to `0.44.0` (not yet released, so this is expected to initially fail testing)
* Adapts the impacted helm `--set` statements due to the proposed change
* Fixes a small issue in the CI pipeline matrix naming scheme
* Closes #1376

fix: update default solo helm chart version

---

src/commands/base.ts
src/commands/node/configs.ts
src/commands/node/handlers.ts
src/commands/node/tasks.ts
src/core/helpers.ts
src/core/model/consensus_node.ts
src/core/platform_installer.ts

* Closes [#1358](https://github.com/hashgraph/solo/issues/1358)

feat(multi-cluster): Update `solo node setup` to support multiple clusters

---

.github/workflows/flow-gcs-test.yaml
.github/workflows/flow-pull-request-checks.yaml
.github/workflows/flow-task-test.yaml
.github/workflows/script/solo_smoke_test.sh
.github/workflows/script/write_diag_script.sh
.github/workflows/zxc-e2e-test.yaml
.github/workflows/zxc-update-readme.yaml
test/e2e/dual-cluster/diagnostics/cluster/deploy.sh
test/e2e/dual-cluster/diagnostics/cluster/manifest.yaml
test/e2e/dual-cluster/kind-cluster-1.yaml
test/e2e/dual-cluster/kind-cluster-2.yaml
test/e2e/dual-cluster/metallb-cluster-1.yaml
test/e2e/dual-cluster/metallb-cluster-2.yaml
test/e2e/dual-cluster/setup-dual-e2e.sh
test/e2e/setup-e2e.sh
version.ts

* Adds the necessary tooling and scripts to support local multi-cluster testing
* Does not enable multi-cluster tests in the CI pipelines 
* Must use load balancers support in Solo with this dual cluster configuration 
* Updates CI pipelines to use the new `setup-dual-e2e.sh` script with a `SOLO_CLUSTER_DUALITY=1` to mimic current behavior
* Partially Resolves #1391

feat: add support for multi-cluster testing via KinD

---

Taskfile.helper.yml
test/e2e/dual-cluster/README.md

* fixed issue with taskfile forcing an incorrect cluster
* context and added a dual cluster readme
* Closes #

fix: fixed issue with taskfile forcing an incorrect cluster and context and added a dual cluster readme

---

src/commands/account.ts
src/commands/flags.ts
src/commands/mirror_node.ts
src/commands/node/tasks.ts
src/commands/relay.ts
src/core/account_manager.ts
src/index.ts
test/e2e/commands/account.test.ts
test/e2e/commands/mirror_node.test.ts
test/e2e/commands/node_local_hedera.test.ts

* feat: add support for --force-port-forward as the top level flag
* by default the flag is set to true to allow Solo to **always** use port forwards for everything it needs to do regardless of what is used for the external address (NodePort/ClusterIP/LoadBalancer)
* It is added as the top-level flag, similar to devMode, to make it common for all commands
* Closes #1403

feat: add support for --force-port-forward as a top level flag

---

src/commands/network.ts

For values arg instead of `config.consensusNodes[consensusNode.cluster]` pass `valuesArgs[consensusNode.cluster]` as well as the return value assign it to the valuesArgs
* Closes # https://github.com/hashgraph/solo/issues/1414

fix(network-command): wrong value passed to addDebugOptions inside the 'network' command

---

src/core/config/remote/remote_config_manager.ts
src/core/config/remote/remote_config_validator.ts
test/e2e/integration/core/remote_config_validator.test.ts

Add support for multi-cluster for `RemoteConfigValidator`:
* pass local config to get the `context` from the component's `cluster` property
* Closes # https://github.com/hashgraph/solo/issues/1406

feat(multi-cluster): make remote config validation compatible with multi-cluster K8 implementation

---

src/commands/network.ts

The error is thrown when `svc[0].status.loadBalancer.ingress` comes in as `undefined`. This PR adds an additional check for this case and gives time to the load balancer to be loaded. However it is possible that the actual issue is that no `ingress` configuration is given when the network has been deployed.
* Closes #1409

fix: Resolve `cannot read properties of undefined `error thrown during `solo network deploy`

---

src/core/platform_installer.ts

Inside the `PlatformInstaller.fetchPlatform()` pass the context down to the `PlatformInstaller.copyFiles()`
* Closes # https://github.com/hashgraph/solo/issues/1420

fix(multi-cluster): fix 'solo node setup' command, failing when running multiple clusters

---

src/commands/node/tasks.ts

* Updates the network activeness checks to support multi-cluster deployments.

fix: ensure network active check supports multi-cluster deployments

---

src/commands/account.ts
src/core/account_manager.ts

* Changed the `AccountManager.updateAccountKeys` to create the secrets inside all available clusters.
* Closes # https://github.com/hashgraph/solo/issues/1395

feat(multi-cluster): updated 'solo account init' to upload secrets to all clusters

---

src/commands/network.ts

This PR changes the `solo network deploy` command when LoadBalancer is enabled. It triggers a `network-node` pods restart after the chart update, forcing an update to `config.txt` 
* Closes #1422

fix: restart network pods after chart update

---

src/commands/network.ts
src/core/constants.ts

* Increases default max attempts from `30` to `60` for the load balancer availability check
* Increases default check delay from `2s` to `5s` for the load balancer availability check
* Makes both the check delay and max attempts configurable via environment variables
* Closes #1460

fix: increase load balancer check waiting time and make values configurable via env

---

src/commands/deployment.ts
src/core/middlewares.ts
src/index.ts

* Added new class `Middlewares` and used it inside root `index.ts`
* Closes # https://github.com/hashgraph/solo/issues/1473

chore(middlewares): move the yargs middlewares inside their own class 'Middlewares'

---

package-lock.json
package.json
src/commands/cluster/configs.ts
src/commands/cluster/tasks.ts
src/commands/explorer.ts
src/commands/flags.ts
src/commands/mirror_node.ts
src/commands/network.ts
src/core/config/remote/common_flags_data_wrapper.ts
src/core/resolvers.ts

Replaced `@listr2/prompt-adapter-enquirer` with `@listr2/prompt-adapter-inquirer`.
* Closes # https://github.com/hashgraph/solo/issues/1201

chore(cli): replace usages of @listr2/prompt-adapter-enquirer with @listr2/prompt-adapter-inquirer

---

src/core/config_manager.ts
src/types/aliases.ts

- added data masking for debug log
- fixed lint warnings
- added access modifiers
- simplified code for ConfigManager
* Closes # https://github.com/hashgraph/solo/issues/1527

chore(security): update the 'ConfigManager.update()' logging to mask sensitive data

---

docs/site/Taskfile.yaml
docs/site/content/User/SoloCommands.md
src/commands/explorer.ts
src/commands/mirror_node.ts
src/commands/network.ts
src/commands/node/configs.ts
src/commands/node/tasks.ts
src/core/account_manager.ts
src/core/config/remote/enumerations.ts
src/core/config/remote/remote_config_manager.ts
src/core/constants.ts
src/core/key_manager.ts
src/core/kube/k8_client/k8_client_base.ts
src/core/kube/k8_client/k8_client_factory.ts
src/core/platform_installer.ts
src/core/profile_manager.ts

* Fixed some tsDoc warning
* There are a few warnings left untouched due to some code were commented out and will be restored later
* Added "excludeExternals" flag to typedoc to ignore warning from external libraries
#1522

chore: fix tsdoc warnings

---

Taskfile.yml

* node keys should be called after deployment command since deployment flag is added to task solo:init command
N/A

fix: node keys should be called after deployment command

---

DEV.md
docs/site/content/User/PlatformDeveloper.md

Original:
Below we describe how you can set up local environment and contribute to `solo`.
Updated:
Below we describe how you can set up a local environment and contribute to `solo`.
Reason for Change:
Added "a" before "local environment" because "environment" is a singular countable noun, which requires an article.
This change improves grammatical correctness and readability.
Original:
with `./gradlew assemble`. If need to running nodes with different versions or releases, please duplicate the repo or build directories in
Updated:
with `./gradlew assemble`. If need to run nodes with different versions or releases, please duplicate the repo or build directories in
Reason for Change:
Changed "running" → "run" to correct the verb form. The phrase should use the base verb "run" rather than …

chore: Enhance Grammar and Clarity in Solo Documentation

---

Taskfile.helper.yml
Taskfile.yml
examples/external-database-test/Taskfile.yml
examples/solo-gke-test/Taskfile.yml
src/commands/cluster/configs.ts
src/commands/cluster/flags.ts
src/commands/cluster/tasks.ts
src/commands/explorer.ts
src/commands/flags.ts
src/commands/mirror_node.ts
src/core/constants.ts
src/core/kube/k8.ts
src/core/kube/k8_client/k8_client.ts
src/core/kube/k8_client/resources/ingress/k8_client_ingresses.ts
src/core/kube/k8_client/resources/ingress_class/k8_client_ingress_classes.ts
src/core/kube/resources/ingress_class/ingress_classes.ts
test/e2e/commands/mirror_node.test.ts
version.ts

* Add new flag to let explorer know what is mirror node namesapce
* Update Taskfile to separate mirror command and explorer command
* Create a new deployment before explorer deploy command
* Install cert-manager chart with explorer deploy command if TLS is enabled
* Install separate ingress controller for mirror and explorer
* Closes #929

feat: new deployment for explorer on different namespace

---

src/commands/node/handlers.ts
src/commands/node/tasks.ts
src/core/command_handler.ts
src/core/errors.ts
src/core/kube/k8_client/resources/lease/k8_client_lease.ts
src/core/kube/k8_client/resources/lease/k8_client_leases.ts
src/core/kube/resources/lease/lease.ts
src/core/kube/resources/lease/leases.ts
src/core/kube/resources/resource_type.ts
src/core/lease/interval_lease.ts
src/core/lease/interval_lease_renewal.ts
src/core/lease/lease_manager.ts
src/core/lease/lease_service.ts
src/core/lease/listr_lease.ts
test/e2e/integration/core/lease.test.ts
test/e2e/integration/core/lease_renewal.test.ts
test/e2e/integration/core/noop_lease_renewal_service.test.ts

* remove v1lease usage outside of `kube` folder
* Closes #1313

fix: remove v1lease usage outside of `kube` folder

---

src/core/config/remote/metadata.ts

* remove use of V1MicroTime for use outside of kube folder
* Closes #1316

fix: remove use of V1MicroTime for use outside of kube folder

---

.github/workflows/script/gcs_test.sh

* Fix network deploy command
Previously network deploy does not need nodeAlias parameter
https://github.com/hashgraph/solo/actions/runs/13793917758/job/38580675404?pr=1634#step:14:200
N/A

fix: add missing parameter

---

package-lock.json
src/data/backend/impl/file-storage-backend.ts
src/data/backend/impl/yaml-file-storage-backend.ts
test/unit/data/backend/impl/file-storage-backend.test.ts
test/unit/data/backend/impl/yaml-file-storage-backend.test.ts
test/unit/data/schema/model/local/local-config.test.ts
test/unit/data/schema/model/remote/remote-config.test.ts

* added storage backend test coverage
* switched data layer class usage of `js-yaml` via `@kubernetes/client` import to `yaml` our chosen YAML library for Solo
* Closes #

chore: added storage backend test coverage

---

src/commands/account.ts
src/commands/deployment.ts
src/commands/flags.ts
src/commands/network.ts
src/commands/node/tasks.ts
src/core/account-manager.ts
src/core/config/local-config.ts
src/core/config/remote/remote-config-manager.ts
src/core/resolvers.ts
test/test-util.ts
test/unit/core/local-config.test.ts

* Removes conditional logic assuming the remote config and its components might be missing
* Fixes bug when prompting for `--num-consensus-nodes` has no effect 
* Closes # https://github.com/hashgraph/solo/issues/1663

fix(multi-cluster): make remote config features required

---

src/core/constants.ts

constants overridable with environmental variables (the constant names are same as the envs that override them):
- `JSON_RPC_RELAY_CHART_URL`
- `MIRROR_NODE_CHART_URL`
- `HEDERA_EXPLORER_CHART_URL`
- `INGRESS_CONTROLLER_CHART_URL`
* Closes # https://github.com/hashgraph/solo/issues/1703

feat(env): Add the ability to override helm chart urls though the envs

---

docs/design/architecture/system/presentation_layer_architecture.md
docs/design/architecture/system/presentation_layer_cli_architecture.md
src/commands/network.ts

* Adds the initial design documentation for the presentation layer and cli components
* Related to #1463 
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been …

docs: add initial version of presentation layer cli design documentation

---

.github/workflows/flow-hugo-publish.yaml
.github/workflows/script/update_md.sh
.gitignore
README.md
docs/content/Developer/Development/TaskTool.md
docs/content/User/AccessHederaServices.md
docs/content/User/DebugLog/index.md
docs/content/User/FAQ.md
docs/content/User/GetStarted.md
docs/content/User/HederaDeveloper.md
docs/content/User/PlatformDeveloper.md
docs/content/User/SDK.md
docs/content/User/SoloCLI.md
docs/content/User/SoloWithMirrorNode.md
docs/content/User/StepByStepGuide.md
docs/content/User/StepByStepGuide.md.template
docs/data/menu/main.yml
src/commands/deployment.ts
src/commands/flags.ts

* `.github/workflows/flow-hugo-publish.yaml` updated to publish `release/0.35` to GitHub Pages
* `.github/workflows/script/update_md.sh` added `solo explorer deploy` command
* fixed getting started infinite loop in docs
* added warnings at top of docs that were out of date
* updated `solo deployment create` to prompt for email, context, and node aliases

fix: updated GitHub Pages docs, fixed `solo deployment create` to prompt for additional flags

---

examples/performance-tuning/solo-gke/mirror-and-explorer-values.yaml
examples/solo-gke-test/mirror-node-values.yaml
resources/mirror-node-values.yaml

* update mirror value files to use default redis for mirror importer and grpc
* Closes #1725 
* \[ ] …

fix: update mirror value files to use default redis for mirror importer and grpc

---

.github/workflows/flow-hugo-publish.yaml
docs/site/Taskfile.yaml
docs/site/config.toml

* Updates the Hugo base URL
* Minor enhancements to the documentation publish workflow
* Closes #1815  …

fix: update docs site for the hiero organization

---

.github/workflows/script/update_md.sh
docs/site/content/en/docs/step-by-step-guide.md
docs/site/content/en/docs/step-by-step-guide.md.template

This pull request updates the Solo deployment scripts and documentation to simplify node configurations and improve resource compatibility. The changes reduce the number of consensus nodes and relay nodes in the deployment process and streamline related commands. Additionally, documentation now includes a note about resource requirements for Docker users.
* Reduced the number of consensus nodes in the `solo deployment add-cluster` command from 2 to 1 for simpler cluster setups. (`.github/workflows/script/update_md.sh`, [.github/workflows/script/update_md.shL46-R49](diffhunk://#diff-2f77041d856d4671898dab659aec7bd1fb35f2760ec4988fb460943e8369b15dL46-R49))
* Removed node-specific identifiers (`-i node1,node2`) from commands such as `solo node keys`, …

fix: lower step-by-step guide to a single node to be able to pass the CI pipeline consistently since block node was added

---

.github/workflows/flow-hugo-publish.yaml

This pull request updates the `.github/workflows/flow-hugo-publish.yaml` file to ensure boolean outputs are explicitly compared to the string `'true'`. This change improves the reliability and clarity of conditional evaluations in the workflow.
Workflow updates:
* Updated the `download-artifacts` parameter to explicitly compare `needs.setup.outputs.download-artifacts` with `'true'`. (`[.github/workflows/flow-hugo-publish.yamlL121-R121](diffhunk://#diff-d5ec53944df3276238a84b403bcc823827d7b0bd6bc5ee2fb56c629a66555752L121-R121)`)
* Updated the `attach-docs-enabled` parameter to explicitly compare `needs.setup.outputs.attach-docs-enabled` with `'true'`. (`[.github/workflows/flow-hugo-publish.yamlL137-R137](diffhunk://#diff-d5ec53944df3276238a84b403bcc8 …

chore: ensure download-artifacts and attach-docs-enabled are boolean values in Hugo Docs build workflow

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-hugo-publish.yaml

This pull request updates GitHub Actions workflows to improve consistency, readability, and functionality. Key changes include renaming output variables for clarity, enhancing logging and debugging, and refining conditional logic for better workflow behavior.
* [`.github/workflows/flow-deploy-release-artifact.yaml`](diffhunk://#diff-f1bcd1ef387efde297c1469d5f2c6ed7ba81f38b14e3d54d270914d1125bb2ccL206-R208): Renamed output variables from `tag-ref` to `tag_ref` and updated related references for consistency. [[1]](diffhunk://#diff-f1bcd1ef387efde297c1469d5f2c6ed7ba81f38b14e3d54d270914d1125bb2ccL206-R208) [[2]](diffhunk://#diff-f1bcd1ef387efde297c1469d5f2c6ed7ba81f38b14e3d54d270914d1125bb2ccL221-R228)
* …

fix: update Hugo workflows to standardize output variable names and improve dry-run handling

---

.github/workflows/flow-hugo-publish.yaml
.github/workflows/zxc-hugo-build.yaml

This pull request includes updates to GitHub Actions workflows to standardize logging and improve clarity in the `flow-hugo-publish` workflow, as well as a minor cleanup in the `zxc-hugo-build` workflow.
**Standardized Logging in `flow-hugo-publish` Workflow:**
* Updated the group markers in `.github/workflows/flow-hugo-publish.yaml` from `:::group::` and `:::endgroup::` to the correct syntax `::group::` and `::endgroup::` for improved compatibility and readability. [[1]](diffhunk://#diff-d5ec53944df3276238a84b403bcc823827d7b0bd6bc5ee2fb56c629a66555752L73-R91) [[2]](diffhunk://#diff-d5ec53944df3276238a84b403bcc823827d7b0bd6bc5ee2fb56c629a66555752L120-R129)
**Cleanup in `zxc-hugo-build` Workflow:**
* Removed an unused conditional statement from the …

chore: fix issue causing hugo build checkout to skip

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-hugo-publish.yaml
.github/workflows/zxc-hugo-build.yaml
.github/workflows/zxc-hugo-publish.yaml
docs/site/Taskfile.github.yaml
docs/site/Taskfile.yaml

This pull request includes updates across several workflow files and task files to improve error handling and streamline the build process. The main changes involve replacing `set -xeo pipefail` with `set -eo pipefail` for better control over script execution, adding necessary environment variables for tasks, and refining task dependencies and commands.
* [`.github/workflows/flow-deploy-release-artifact.yaml`](diffhunk://#diff-f1bcd1ef387efde297c1469d5f2c6ed7ba81f38b14e3d54d270914d1125bb2ccL142-R142): Replaced `set -xeo pipefail` with `set -eo pipefail` in multiple job steps to simplify error handling during script execution. [[1]](diffhunk://#diff-f1bcd1ef387efde297c1469d5f2c6ed7ba81f38b14e3d54d270914d1125bb2ccL142-R142) …

chore: fix hugo build issue not picking up GH_TOKEN since it is in a Taskfile task call

---

.github/workflows/flow-gcs-test.yaml

This pull request modifies the workflow configuration in `.github/workflows/flow-gcs-test.yaml` to update the conditional logic for running the `gcs-storage-test` job.
Workflow logic update:
* [`.github/workflows/flow-gcs-test.yaml`](diffhunk://#diff-ace6fa1c3b0eccf534e8f0a7b9c6da5458d0ba2ca6ced6fd1ab78e7992f4e7e1L38-R38): Changed the `if` condition to exclude pull requests from forks, ensuring the job only runs for pull requests originating from the main repository.
* Closes #
* Related to #
* \[ ] Any technical debt has been documented as a separate issue …

chore: update GCS storage test condition to exclude forked repositories

---

README.md
docs/design/archive/multi_user_cluster_support.md

- Fixed spelling error in docs/design/archive/multi_user_cluster_support.md
- Changed "accross" to "across" in clusters configuration section
- Updated README.md with improved node version switch instructions
Documentation improvements for better readability and correctness.

docs: Correct "accross" to "across" in cluster configuration docs

---

src/commands/node/flags.ts
test/test-utility.ts

* `solo node logs` - remove the `--node-aliases` flag
* Closes # https://github.com/hiero-ledger/solo/issues/2198
* \[ ] This PR added unit …

chore: remove '--node-aliases' for 'solo node logs' command

---

.codacy.yaml

This pull request updates the `.codacy.yaml` configuration file to switch the ESLint engine from version 8 to version 9 and specify a new configuration file, while excluding a particular file from analysis.
Configuration updates:
* [`.codacy.yaml`](diffhunk://#diff-c5a5c4ae84ac2b668f86b7aa44844393495c110e6da20e897455bedb8e900c7eR1-R9): Disabled `eslint-8`, enabled `eslint-9` with `eslint.config.mjs` as the configuration file, and added `tsdoc-plugin-macros.mjs` to the `exclude_paths` list.
* Closes #
* Related to #
* \[ ] Any technical debt has been …

chore: create codacy configuration file

---

.github/workflows/script/solo_smoke_test.sh
examples/Taskfile.examples.yml
examples/Taskfile.yml

* when a shell env var `SOLO_CLUSTER_NAME` is set, cluster are setup to use the define cluster kind-$SOLO_CLUSTER_NAME}
but this line make explorer uses cluster context defined in env section of task file, not the shell environment
```
EXPLORER_CLUSTER_CONTEXT: kind-{{.SOLO_CLUSTER_NAME}}
```
* Closes #2299 
* Related to #
* …

fix: explorer deploy use incorrect env variable in task file

---

src/commands/account.ts
src/commands/deployment.ts
src/commands/explorer.ts
src/commands/mirror-node.ts
src/commands/network.ts
src/commands/relay.ts
src/core/yargs-command.ts

This pull request focuses on removing redundant logging of the `argv` object across various command handlers in the codebase. These changes streamline the logging output and ensure that only relevant information is logged during command execution.
* Removed `argv` logging in the handlers for `account init`, `account create`, `account update`, and `account get` commands in `src/commands/account.ts`. [[1]](diffhunk://#diff-a6cd96f569fd82c8eeae60c972cbedb3b7ba1e680793e399a65049c22de0c176L773) [[2]](diffhunk://#diff-a6cd96f569fd82c8eeae60c972cbedb3b7ba1e680793e399a65049c22de0c176L797) [[3]](diffhunk://#diff-a6cd96f569fd82c8eeae60c972cbedb3b7ba1e680793e399a65049c22de0c176L821) [[4]](diffhunk://#diff-a6cd96f569fd82c8eeae60c972cbedb3b7ba1e680793e399a65049c …

chore: remove unnecessary logging of argv in command handlers

---

src/commands/account.ts

* Add flag to allow user to show private key during account create
* Closes #2354 
* Related to #
* \[ …

feat: add flag to private key

---

docs/site/content/en/templates/step-by-step-guide.template.md
src/commands/cluster/tasks.ts

This pull request includes minor documentation fixes and a code comment to clarify behavior in the cluster command tasks. The documentation changes correct a bash command, and the code change adds a TODO comment about RBAC role installation.
Documentation fixes:
* Fixed a typo in the bash cleanup command by removing an unnecessary semicolon in two places in `step-by-step-guide.template.md`. [[1]](diffhunk://#diff-92de30b75d48fa7e325a6b3f0e491e75c7e0d0bc0bccf7f1f26961296bd41d7eL107-R107) [[2]](diffhunk://#diff-92de30b75d48fa7e325a6b3f0e491e75c7e0d0bc0bccf7f1f26961296bd41d7eL680-R680)
Code clarification:
* Added a TODO comment in `ClusterCommandTasks` noting that skipping installation may also skip installing the RBAC role.
* Closes #
* Related to #
* \[ ] This PR added tests (unit, …

chore: fixed a typo in the bash cleanup command by removing an unnecessary semicolon in two places in `step-by-step-guide.template.md`

---

src/core/platform-installer.ts

- Adds a `sync` prior to calling the `extract-platform.sh` script
- Removes the `sleep for 2 seconds` from the `fetchPlatform` method in favor of `sync` prior to executing the `extract-platform.sh` script.
* Closes #2503
* \[x] When this PR merges the commits will …

fix: replace 2 second sleep with sync after remote copyFiles

---

.github/workflows/flow-hugo-publish.yaml

This pull request makes a small change to the Hugo docs publishing workflow. The condition for running the `hugo-docs-publish` job has been simplified by removing the check for a successful build output.
- Simplified the `if` condition for the `hugo-docs-publish` job in `.github/workflows/flow-hugo-publish.yaml` by removing the requirement that `needs.hugo-docs-build-main.outputs.build_succeeded == 'true'`.
* Closes #2297 
* Related to #
* \[ ] Any `package.json` changes have been explained to and approved by a …

fix: Hugo docs build fix v2

---

resources/templates/application.properties
resources/templates/settings.txt

This pull request updates the `resources/templates/settings.txt` configuration file to tune the performance and scaling parameters for MerkleDB and virtual map operations.
Performance and scaling configuration updates:
* Added `merkleDb.initialCapacity` to set the initial capacity for MerkleDB to 1,000,000.
* Added `merkleDb.maxNumOfKeys` to set the maximum number of keys for MerkleDB to 500,000,000.
* Added `merkleDb.hashesRamToDiskThreshold` to control when hashes are moved from RAM to disk, set to 0.
* Added `virtualMap.copyFlushCandidateThreshold` to set the threshold for flushing virtual map copy candidates to 100,000,000.
* Closes https://github.com/hiero-ledger/solo/issues/2696
* Related to #
* \[ ] This PR updated …

fix: add initial capacity setting for merkleDb in settings
