hiero-ledger/solo

src/core/constants.mjs
* allow user to specify solo home directory using environment variable.
* Closes #40
=> fix: support SOLO_HOME environment variable for home directory

README.md, jest.config.mjs, package-lock.json, package.json, test/jest/fail_fast.mjs
* fail fast when a test fails
* minor update to README because of `npm run format`
* Closes #58
=> test: fail fast when a test execution fails

README.md
* Remove dollar sign so users directly copy from text box and paste to command line
* Fix incorrect github links
N/A
=> chore: update readme document

README.md
* update the readme to mention the fst chart version of 0.22.0
=> chore: update the readme to mention the fst chart version of 0.22.0

.remarkrc.yml, DEV.md
* add developer instructions
* Closes #
=> chore: add developer instructions

.github/workflows/flow-pull-request-checks.yaml, .github/workflows/zxc-code-analysis.yaml
* Enables code coverage reporting via Codacy
* Closes #90
=> chore(ci): enable codacy coverage reporting

.github/workflows/flow-build-application.yaml
* Enables Codacy reporting on the `main` branch by virtue of the following:
* Updates the `flow-build-application.yaml` workflow to enable the codacy option on the existing step.
* Fixes several `if:` evaluations to properly handle several edge cases. 
* Closes #107
=> chore(ci): enable codacy coverage reporting for main branch merges

README.md, test/e2e/setup-e2e.sh
* update readme and setup e2e script to remove references to create namespace
* Closes #102
=> chore: update readme and setup e2e script to remove references to create namespace

.github/workflows/flow-build-application.yaml
* Fixes a coverage reporting bug in #107 
* Closes #112
=> chore(ci): ensure e2e coverage reports are analyzed for main branch commits

src/commands/network.mjs, src/commands/node.mjs
* Update incorrect log messages for destroy network and stop nodes
* Closes #131
=> fix: updated incorrect log messages

test/e2e/commands/network.test.mjs
* add network command end to end test
* Closes #138
=> test: add network command end to end test

DEV.md, jest.config.mjs, package-lock.json, package.json, test/e2e/commands/network.test.mjs, test/testSequencer.mjs
* Using a random test sequencer to run unit tests and end-to-end test
* Random seed can be retrieved from log to reproduce issues if required
* Closes #183
=> test: add random test sequencer

DEV.md, README.md, src/commands/base.mjs, src/commands/flags.mjs, src/commands/relay.mjs, src/core/chart_manager.mjs
* fix: solo relays command is not working
* change `solo relays install/uninstall` to `solo relays deploy/destroy` for consistency with `solo mirror deploy/destroy`
* update README with command output
* auto-format *.md files
* Closes #185
=> fix: solo relays command is not working

src/commands/node.mjs, src/core/account_manager.mjs, src/core/k8.mjs, src/core/key_manager.mjs
* Fix javasript doc error reported by jsDoc
* Closes #192
=> feat: fix javascript documentation

.github/workflows/zxc-compile-code.yaml
* remove helm & java install from ci pipeline
* Closes #161
=> feat: remove helm & java install from ci pipeline

.github/workflows/flow-build-application.yaml, .github/workflows/flow-update-readme.yaml, README.md.template, src/commands/node.mjs, src/core/helpers.mjs
- correct a typo in `node.mjs`
- update refresh command description
- add jsdoc for `helper.mjs` `validatePath()`
- updates to `flow-update-readme.yaml` to make when it runs more consistent and fix:
- GITHUB_TOKEN is not signing commits
- updated to only run when pushes occur to `main` branch
* Closes #223
=> fix: address PR comments from #211

.github/workflows/flow-pull-request-checks.yaml, .github/workflows/zxc-compile-code.yaml
* enable code coverage for dependent bot
* Closes #237
=> ci: enable code coverage for dependent bot

resources/templates/application.properties, src/commands/node.mjs, src/core/k8.mjs, src/core/key_manager.mjs, test/e2e/commands/node.test.mjs, test/test_util.js, test/unit/commands/node.test.mjs
* add `solo node add` subcommand
* Closes #115
=> feat: add `solo node add` subcommand

.github/workflows/zxc-compile-code.yaml, test/e2e/commands/mirror_node.test.mjs, test/unit/core/dependency_managers/dependency_manager.test.mjs, test/unit/core/key_manager.test.mjs
* Increase timeout threshould for a few frequently failed tests due to timeout
* Add install wget since the new versoin of helm/kind-action [would fail due to could not find wget](https://github.com/hashgraph/solo/actions/runs/8822946284/job/24257833275)
* Closes N/A
=> test: increase time out

src/commands/network.mjs
* Fix the incorrect pod name
* Closes #319
=> fix: the wrong pod name 

test/e2e/commands/mirror_node.test.mjs
* Refactor mirror node test into fine grained steps
* Closes #334
=> test: split mirror node test into more detailed steps

.github/workflows/flow-pull-request-formatting.yaml
Update conventional-pr-title-check-action with step-security version
* Closes #343
=> ci: Update conventional-pr-title-check-action with step-security version

src/commands/relay.mjs, src/core/constants.mjs, src/core/helpers.mjs, src/core/logging.mjs, src/core/profile_manager.mjs, src/core/shell_runner.mjs, src/core/zippy.mjs
* move getNodeAccountMap from constants to helpers
* remove lint and IDE warnings
* remove unused constants
* Closes #373 
* required by #364
=> refactor: move getNodeAccountMap from constants to helpers

src/commands/flags.mjs, src/commands/network.mjs, src/commands/prompts.mjs, src/core/k8.mjs, test/e2e/commands/network.test.mjs
* Add a new flag for network destroy command
* Closes #77
=> test: add delete secrets flag

resources/templates/log4j2.xml, resources/templates/settings.txt
* Updates the default `settings.txt` file to match mainnet.
* Updates the default `log4j2.xml` file to match mainnet.
* Closes #383
=> fix: update the default settings and log4j2 configuration files

README.md.template, src/core/account_manager.mjs
* update README for hashgraph sdk log
* Closes #331
=> ci: update README for hashgraph sdk log

docs/content/_index.md, docs/hugo.toml
Adds new home page to the official Solo Documentation. 
* Closes #406
=> docs: Add home page to documentation

docs/content/_index.md, docs/content/contribution/contribution.md, docs/content/contribution/docs.md, docs/content/getting-started/deploy.md, docs/content/getting-started/installation.md, docs/content/getting-started/setup.md, docs/data/menu/main.yml, docs/data/menu/more.yml
This PR adds the needed changes to the Navigation bar to support new pages like Getting Started, Installation and more
* Closes #411
=> docs: Improve Navigation Bar

docs/content/getting-started/deploy.md, docs/content/getting-started/installation.md, docs/content/getting-started/setup.md
This PR aims to continue the effort of expading official documentation, by separting the steps to get solo running.
* Closes #412
=> docs: add getting started page

.github/workflows/flow-deploy-release-artifact.yaml, .github/workflows/flow-hugo-publish.yaml, .github/workflows/flow-pull-request-formatting.yaml, .github/workflows/flow-update-readme.yaml, .github/workflows/zxc-code-analysis.yaml, .github/workflows/zxc-code-style.yaml, .github/workflows/zxc-e2e-test.yaml, .github/workflows/zxc-env-vars.yaml, .github/workflows/zxc-unit-test.yaml
* Updates CI workflows to use the Latitude.sh self-hosted runners.
* Closes #483
=> ci: update workflows to use latitude.sh based runners

.github/workflows/zxc-e2e-test.yaml, src/commands/node.mjs, test/e2e/commands/node-add-local.test.mjs, test/e2e/commands/node-add.test.mjs, test/test_add.mjs
* added new e2e test node-add-local.test.mjs
* moved original function of node-add.test.mjs to a shared file test_add.mjs
* Closes #430
=> feat: add local build support for node add command

src/commands/node.mjs
…dating the podNames when they change
* set chart directory in `solo node update` to avoid unintentional upgrade of docker containers
* download the key files from from the freeze
* update the podName after they restart
=> fix: set chart directory in `solo node update`, download key files, and update podNames

.github/workflows/zxc-e2e-test.yaml, src/core/constants.mjs, src/core/k8.mjs, test/test_util.js, version.mjs
* update hedera version to 0.54
* add retry in k8.copyfrom() as work around of intermittent "TAR_BAD_ARCHIVE: Truncated input" error 
N/A
=> ci: update hedera version to 0.54

README.md
Add the requirement matrix table to the readme with all the requirements for the current version of solo
https://github.com/hashgraph/solo/issues/503
=> docs: add the requirement table for the current version of solo

.github/workflows/zxc-code-analysis.yaml, .github/workflows/zxc-e2e-test.yaml
* Consolidating E2E test report and publish steps
* Closes #573
=> ci: consolidating E2E test report and publish steps

solo-compose/docker-compose.yml, solo-compose/setup-runner.sh
Add Docker Compose and a script to set up the local testing environment
* Closes # [568](https://github.com/hashgraph/solo/issues/568)
=> chore(dev-environment): Add Docker Compose and script for local testing environment

.github/workflows/flow-deploy-release-artifact.yaml
* more update readme testing
* Closes #594
=> fix: more update readme testing

.github/workflows/flow-deploy-release-artifact.yaml, .github/workflows/flow-update-readme.yaml
* troubleshooting commit-hash in deploy and release
* Closes #594
=> fix: troubleshooting commit-hash

.github/workflows/flow-deploy-release-artifact.yaml, .github/workflows/flow-update-readme.yaml
* removed extra workflow steps used for debugging
* Closes #594
=> chore(CICD): removed extra workflow steps used for debugging

src/commands/flags.mjs, src/commands/mirror_node.mjs, src/commands/network.mjs, src/commands/prompts.mjs, src/core/k8.mjs, test/e2e/commands/mirror_node.test.mjs, test/e2e/commands/network.test.mjs, test/test_util.js
* Relocate flags used for mirror node deployment
* Closes #431
=> chore: Relocate flags used for mirror node deployment

src/commands/account.mjs, src/commands/mirror_node.mjs, src/commands/network.mjs, src/commands/node.mjs, src/commands/relay.mjs
* update command description to `solo network`
* Closes #612
=> chore: update command description

examples/custom-network-config/Taskfile.yml, examples/custom-network-config/init-containers-values.yaml, examples/custom-network-config/list-external-ips.gotemplate, examples/custom-network-config/settings.txt
* Adds an example demonstrating deployment of custom sized nodes.
* Closes #632
=> docs: adds an example showing custom sized consensus nodes

.github/workflows/flow-build-application.yaml, .github/workflows/flow-pull-request-checks.yaml, .github/workflows/templates/template.flow-build-application.yaml, .github/workflows/templates/template.flow-pull-request-checks.yaml, .github/workflows/zxc-unit-test.yaml
* set matrix strategy fail-fast to false
* Closes #696
=> ci: set matrix strategy fail-fast to false

.github/workflows/flow-deploy-release-artifact.yaml, .github/workflows/flow-hugo-publish.yaml, .github/workflows/flow-pull-request-formatting.yaml, .github/workflows/zxc-code-analysis.yaml, .github/workflows/zxc-code-style.yaml, .github/workflows/zxc-e2e-test.yaml, .github/workflows/zxc-env-vars.yaml, .github/workflows/zxc-unit-test.yaml, .github/workflows/zxc-update-readme.yaml
Add harden runner step to all jobs. Change "contents" permission for the zxc-env-vars workflow.
* Closes #706
=> ci: Change "contents" persmission and add hardened runner step

test/e2e/commands/account.test.ts, test/e2e/commands/mirror_node.test.ts, test/e2e/commands/network.test.ts, test/e2e/commands/node_add.test.ts, test/e2e/commands/node_add_local.test.ts, test/e2e/commands/node_delete.test.ts, test/e2e/commands/node_local_hedera.test.ts, test/e2e/commands/node_local_ptt.test.ts, test/e2e/commands/node_pem_kill.test.ts, test/e2e/commands/node_pem_stop.test.ts, test/e2e/commands/node_update.test.ts, test/e2e/commands/node_upgrade.test.ts, test/e2e/commands/relay.test.ts, test/e2e/commands/separate_node_add.test.ts, test/e2e/commands/separate_node_delete.test.ts, test/e2e/e2e_node_util.ts, test/e2e/integration/core/account_manager.test.ts, test/e2e/integration/core/platform_installer_e2e.test.ts, test/test_add.ts, test/test_util.ts
* fix bootstrap network issues when we switched to Mocha
* Closes #705
=> chore(tests): fix bootstrap network issues when we switched to Mocha

.github/workflows/flow-deploy-release-artifact.yaml
* patch issue with dist folder not showing up
* Closes #702
=> fix: patch issue with dist folder not showing up

package.json
* bump package.json version for people running locally
* Closes #
=> chore: bump package.json version for people running locally

eslint.config.mjs, src/commands/account.ts, src/commands/cluster.ts, src/commands/init.ts, src/commands/mirror_node.ts, src/commands/network.ts, src/commands/node/index.ts, src/commands/relay.ts
* eslint setting no this alias except self (added `// TODO remove` for allowing self)
* Closes #
=> chore: eslint setting no this alias except self

src/core/platform_installer.ts
* Added a delay before calling script to extract platform code
* Closes #954
=> fix: add delay before calling script

README.md
Removed the following as per the comments on #999 & #998:
```
* Run `npm clean install` or `npm ci`
* Run `npm run build`
```
* Follows up from #998 & #999.
=> docs(README): Updated the "Install Solo" section.

HelperTasks.yml, Taskfile.yml, examples/custom-network-config/Taskfile.yml, examples/performance-tuning/Latitude/Taskfile.yml, examples/performance-tuning/solo-perf-test/Taskfile.yml, examples/solo-gke-test/Taskfile.yml, src/commands/flags.ts, src/core/profile_manager.ts, src/core/templates.ts, test/unit/core/profile_manager.test.ts
* fixed genesis-network.json file lock issue
* commented out solo chart and hedera version overrides in taskfile
* updated taskfile to work without solo chart and hedera version overrides
* updated taskfile to clean up tmp files
* updated Solo to use hedera version default when no release tag is provided
* Closes #1027
=> fix: fixed genesis-network.json file lock issue

docs/content/User/StepByStepGuide.md, docs/content/User/StepByStepGuide.md.template
* fix `docs/content/User/StepByStepGuide.md` lint failure
* Closes #1080
=> chore: fix `docs/content/User/StepByStepGuide.md` lint failure

docs/content/User/StepByStepGuide.md, examples/README.md, src/core/lease/interval_lease.ts
* Addresses the true underlying problem impacting the lease acquire method when an expired lease is present in the cluster.
* Initiates a lease transfer if an existing expired lease is present when the `acquire` method is called to ensure the lease holder information is properly updated.
* Closes #1104
=> fix(lease): reworks the previous fix addressing renewal issues

.github/workflows/zxc-update-readme.yaml
* fix commit message of auto update
* Closes #1103
=> fix: commit message of auto update

README.md
* fix: clarify how to use nvm
* Closes #1124
=> fix: clarify how to use nvm

version.ts
* bump versions of hedera, json rpc relay, and mirror node
* Closes #
=> fix: bump versions of hedera, json rpc relay, and mirror node

.github/CODEOWNERS
Updates codeowners to remove devops-ci and add platform-ci
=> chore: Update codeowners to change devops-ci to platform-ci

examples/custom-network-config/application.properties, examples/performance-tuning/solo-gke/application.properties, examples/solo-gke-test/application.properties, resources/templates/application.properties
Disables the block stream generation
* Closes #1167
=> chore: Temporarily disable block streams

src/core/constants.ts
* Normalize mirror node resources path
* Closes #1170
=> fix: Normalize mirror node resources path

.github/workflows/script/solo_smoke_test.sh, src/commands/mirror_node.ts, src/core/constants.ts, test/e2e/commands/mirror_node.test.ts, version.ts
* Updates the location and version of the Hedera Explorer chart
* Renames two constants to fix typographical errors
* Closes #1186
=> fix: update hedera explorer chart version and location

src/commands/explorer.ts
* Remove non-existing functions
Closes #1198
=> fix: merge error due to change of remote_config_tasks

src/core/kube/t_directory_data.ts
* fixed merge issue with incorrect license header
* Closes #
=> fix: fixed merge issue with incorrect license header

src/core/kube/config_maps.ts, src/core/kube/leases.ts, src/core/kube/namespace_name.ts, src/core/kube/namespaces.ts, src/core/kube/pods.ts, src/core/kube/pvcs.ts, src/core/kube/secrets.ts, src/core/kube/services.ts
* add NamespaceName to k8 interfaces
* Closes #1251
=> refactor: add NamespaceName to k8 interfaces

src/core/kube/clusters.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/kube/k8_client/k8_client_clusters.ts
* Adds an implementation of the `Clusters` fluent interface.
* Closes #1241
=> feat: add clusters fluent interface implementation

src/commands/mirror_node.ts, src/core/constants.ts, src/core/kube/container_name.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/kube/kube_errors.ts, src/core/kube/pod.ts, test/e2e/integration/core/chart_manager.test.ts, test/e2e/integration/core/k8_e2e.test.ts
* add k8.ContainerName
* implement k8.ContainerName use throughout the codebase
* Closes #1254
=> refactor: add k8.ContainerName and implement throughout the codebase

src/commands/mirror_node.ts, src/commands/node/tasks.ts, src/core/kube/container_ref.ts, src/core/kube/errors/namespace_name_invalid_error.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/kube/pod.ts, src/core/platform_installer.ts, test/e2e/commands/node_delete.test.ts, test/e2e/commands/node_update.test.ts, test/e2e/commands/node_upgrade.test.ts, test/e2e/commands/separate_node_delete.test.ts, test/e2e/commands/separate_node_update.test.ts, test/e2e/commands/separate_node_upgrade.test.ts, test/e2e/integration/core/k8_e2e.test.ts, test/e2e/integration/core/platform_installer_e2e.test.ts, test/test_util.ts
* create k8.ContainerRef
* implement k8.ContainerRef across codebase
* Closes #1255
=> refactor: create k8.ContainerRef and implement across codebase

src/core/kube/contexts.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/kube/k8_client/k8_client_base.ts, src/core/kube/k8_client/k8_client_containers.ts, src/core/kube/k8_client/k8_client_object_meta.ts, src/core/kube/k8_client/k8_client_pods.ts, src/core/kube/k8_client/k8_client_service.ts, src/core/kube/k8_client/k8_client_services.ts, src/core/kube/load_balancer_ingress.ts, src/core/kube/load_balancer_status.ts, src/core/kube/object_meta.ts, src/core/kube/resource_operation.ts, src/core/kube/service.ts, src/core/kube/service_port.ts, src/core/kube/service_spec.ts, src/core/kube/service_status.ts, src/core/kube/services.ts
* Adds `Service` interface and related interfaces
* Adds `K8ClientServices` fluent interface implementation
* Closes #1244
=> feat: add service and services fluent interface implementation

src/commands/node/tasks.ts, src/core/container_init.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/network_nodes.ts, test/e2e/commands/account.test.ts, test/e2e/commands/mirror_node.test.ts, test/e2e/commands/network.test.ts, test/e2e/commands/node_delete.test.ts, test/e2e/commands/node_local_hedera.test.ts, test/e2e/commands/node_local_ptt.test.ts, test/e2e/commands/node_update.test.ts, test/e2e/commands/node_upgrade.test.ts, test/e2e/commands/relay.test.ts, test/e2e/commands/separate_node_add.test.ts, test/e2e/commands/separate_node_delete.test.ts, test/e2e/commands/separate_node_update.test.ts, test/e2e/commands/separate_node_upgrade.test.ts, test/e2e/e2e_node_util.ts, test/test_add.ts, test/test_util.ts
* created NetworkNode and moved k8 related methods into it and updated codebase to use
* Closes #1266
=> refactor: created NetworkNode and moved k8 related methods into it and updated codebase to use

src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/kube/k8_client/k8_client_pvcs.ts
* added pvcs fluent interface implementation
* Closes #1246
=> refactor: added pvcs fluent interface implementation

src/core/kube/k8_client.ts, src/core/kube/k8_client/k8_client_namespaces.ts, src/core/kube/namespaces.ts
* added namespaced fluent interface implementation
* Closes #1248
=> refactor: added namespaced fluent interface implementation

src/commands/cluster/tasks.ts, src/core/config/local_config.ts, src/core/config/remote/remote_config_manager.ts, src/core/kube/clusters.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/index.ts, test/e2e/integration/core/k8_e2e.test.ts, test/unit/commands/cluster.test.ts
=> refactor: utilize k8.clusters methods

src/commands/cluster/configs.ts, src/commands/cluster/tasks.ts, src/commands/deployment.ts, src/core/config/local_config.ts, src/core/config/remote/remote_config_manager.ts, src/core/kube/contexts.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/index.ts, test/e2e/integration/core/k8_e2e.test.ts, test/unit/commands/cluster.test.ts
=> refactor: utilize k8.contexts methods

src/core/config/remote/remote_config_manager.ts, src/core/kube/config_maps.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, test/unit/commands/network.test.ts
=> refactor: utilize k8.ConfigMaps methods

src/core/cluster_checks.ts, src/core/kube/ingress_class.ts, src/core/kube/ingress_classes.ts, src/core/kube/k8.ts, src/core/kube/k8_client.ts, src/core/kube/k8_client/k8_client_ingress_class.ts, src/core/kube/k8_client/k8_client_ingress_classes.ts
* add k8 ingress classes list implementation
* Closes #1263
=> refactor: add k8 ingress classes list implementation

src/core/cluster_checks.ts, src/core/kube/k8_client/k8_client_pod.ts, src/core/kube/k8_client/k8_client_pods.ts, src/core/kube/pod.ts, src/core/kube/pods.ts
* add k8 pods list for all namespaces implementation
* Closes #1262
=> refactor: add k8 pods list for all namespaces implementation

src/core/kube/k8_client/k8_client_services.ts, src/core/kube/service_name.ts, src/core/kube/service_ref.ts, src/core/kube/services.ts, test/e2e/integration/core/k8_e2e.test.ts
* add k8.services().create()
* Closes #1260
=> refactor: add k8.services().create()

test/e2e/kind-cluster.yaml, test/e2e/setup-e2e.sh
* Resolves rate limiting on docker hub resulting in erroneous E2E test failures.
* Closes #1324
=> ci: resolve issues with docker hub rate limits causing e2e test failures

src/commands/base.ts, test/unit/commands/base.test.ts
* add BaseCommand.getContexts() method
* Relates to #1357
=> feat: add BaseCommand.getContexts() method

.github/workflows/flow-build-application.yaml, .github/workflows/flow-pull-request-checks.yaml
* changed e2e matrix max from 5 to 3
* Closes #
=> ci: changed e2e matrix max from 5 to 3

.github/workflows/script/gcs_test.sh
* Fix the test script of saving stream files to storage
N/A
Test result
https://github.com/hashgraph/solo/actions/runs/13333366427
=> fix: test script of google storage

src/commands/node/tasks.ts, src/core/account_manager.ts
* Fixes the node staking logic to support multi-cluster deployments
=> fix: ensure staking updates support multi-cluster deployments 

src/core/helpers.ts, version.ts
=> fix: use better internal IPs for 0.58.5+

docs/content/User/HederaDeveloper.md, docs/content/User/PlatformDeveloper.md, docs/content/User/SoloWithMirrorNode.md, docs/content/User/StepByStepGuide.md.template
* Update document with deployment command
N/A
=> chore: Update document with deployment command

src/commands/network.ts
* updates solo network refresh to handle multiple clusters
* Closes #1441
=> refactor: multiple cluster support for `solo network refresh`

src/commands/account.ts, src/types/aliases.ts
Removed all warnings in `AccountCommand`
* Closes # https://github.com/hashgraph/solo/issues/1518
=> chore: fix warnings in AccountCommand

resources/mirror-node-values.yaml
* reduce TPS value for pinger in mirror-node-values.yaml
* Closes #1510
=> fix: reduce TPS value for pinger in mirror-node-values.yaml

Taskfile.yml, examples/performance-tuning/solo-gke/Taskfile.yml, examples/solo-gke-test/Taskfile.yml, src/commands/flags.ts, test/e2e/dual-cluster/setup-dual-e2e.sh, test/e2e/setup-e2e.sh
* add `-d` alias for `--deployment` flag in flags.ts
* Closes #1508
=> feat: add `-d` alias for `--deployment` flag in flags.ts

src/commands/node/tasks.ts, src/core/genesis_network_models/genesis_network_data_constructor.ts, src/core/kube/k8_client/resources/namespace/k8_client_namespaces.ts, src/core/kube/resources/object_meta.ts, src/core/kube/resources/pod/pods.ts, src/core/kube/resources/pvc/pvc_name.ts, src/core/kube/resources/pvc/pvc_ref.ts, src/core/lease/interval_lease.ts, src/core/lease/lease.ts, src/core/lease/lease_manager.ts, src/core/platform_installer.ts, test/test_container.ts, test/unit/core/profile_manager.test.ts
* fix: await chartManager upgrade for asynchronous operation in tasks.ts
* removed unused imports
* shortened import paths to remove warnings
* Closes #
=> fix: await chartManager upgrade for asynchronous operation in tasks.ts

resources/profiles/custom-spec.yaml
* Fix web3 pod crash due to out of memory
* Closes #1489
=> fix: increase resource of web3 pod

src/commands/account.ts
* Each account create new send transaction first then send query to get account id, round trip time is about 2 seconds
* Change to use subtask to create account in parallel mode
* Closes #1545
---
✔ Initialize [0.1s]
✔ Acquire lease - lease acquired successfully, attempt: 1/10
✔ create the new account [5s]
✔ Create accounts [0] [0.8s]
✔ Create accounts [1] [0.8s]
✔ Create accounts [2] [2s]
✔ Create accounts [3] [0.9s]
✔ Create accounts [4] [0.7s]
✔ Create accounts [5] [2s]
✔ Create accounts [6] [0.8s]
✔ Create accounts [7] [0.9s]
✔ Create accounts [8] [0.8s]
✔ Create accounts [9] [0.7s]
✔ Create accounts [10] [0.6s]
✔ Create accounts [11] [0.6s]
✔ Create accounts [12] [0.4s]
✔ Create accounts [13] [0.4s]
✔ Create accounts [14] [0.6s]
✔ Create …
=> feat: use subtask to create many account in parallel

.github/workflows/zxc-update-readme.yaml
* fix the issue that caused the update readme job to fail
* Closes #
=> ci: update zxc-update-readme.yaml

.github/workflows/zxc-e2e-test.yaml, solo.ts, src/commands/account.ts, src/commands/cluster/configs.ts, src/commands/cluster/tasks.ts, src/commands/deployment.ts, src/commands/explorer.ts, src/commands/init.ts, src/commands/mirror_node.ts, src/commands/network.ts, src/commands/relay.ts, src/core/config/local_config.ts, src/core/config/remote/remote_config_manager.ts, src/core/constants.ts, src/core/dependency_injection/container_init.ts, src/core/logging.ts, src/core/middlewares.ts, src/core/yargs_command.ts, src/index.ts, test/e2e/commands/dual_cluster_full.test.ts, test/test_container.ts, test/test_util.ts, test/unit/commands/network.test.ts
* fix: yargs command async missing
* update dual cluster full e2e test to run node keys test
* Updated error handling for commands 
* Removed process.exit except for new logging methods that uses a callback to first flush the logs to disk then exit 
* Improved pathway for remote config to load early using local config
* Closes #
=> fix: yargs command async missing

.github/workflows/zxc-update-readme.yaml
* Change workflow token, skip GPG import step for dry run
* Closes #1574
=> fix: token flow error

src/commands/node/tasks.ts, version_test.ts
* node add/delete helm upgrade failure
* Closes #1624
=> fix: node add/delete helm upgrade failure

src/core/lease/interval_lease.ts
* log error message in tryRenew method for better debugging
* Closes #
=> fix: log error message in tryRenew method for better debugging

.github/workflows/flow-hugo-publish.yaml
* update concurrency settings in flow-hugo-publish.yaml
* Closes #
=> ci: update concurrency settings in flow-hugo-publish.yaml

eslint.config.mjs, package-lock.json, package.json, src/commands/node/tasks.ts, test/e2e/commands/node_update.test.ts, test/e2e/commands/separate_node_delete.test.ts, test/e2e/commands/separate_node_update.test.ts, test/unit/commands/cluster.test.ts, test/unit/core/config/remote/remote_config_data_wrapper.test.ts
* added eslint remove unused imports plugin
* Closes #
=> chore: added eslint remove unused imports plugin

src/core/cluster_checks.ts, src/core/config/remote/remote_config_data_wrapper.ts, src/core/config/remote/remote_config_manager.ts, src/core/kube/k8_client/resources/config_map/k8_client_config_map.ts, src/core/kube/k8_client/resources/config_map/k8_client_config_maps.ts, src/core/kube/resources/config_map/config_map.ts, src/core/kube/resources/config_map/config_maps.ts
* removed V1ConfigMap usage outside of kube folder
* Closes #1314
=> chore: removed V1ConfigMap usage outside of kube folder

docs/design/architecture/system/architecture_overview.md, docs/design/architecture/system/business_layer_architecture.md, docs/design/architecture/system/data_layer_architecture.md, docs/design/architecture/system/internal_data_model.md, docs/design/architecture/system/workflow_layer_architecture.md
* Adds design docs for the following
* Architecture Overview
* Business Layer
* Data Layer
* Workflow Layer
* Partially Addresses #1463
=> feat: add design docs for the new architecture

version.ts
* update HEDERA_PLATFORM_VERSION to v0.59.4
* Closes #
=> chore: update HEDERA_PLATFORM_VERSION to v0.59.4

package.json, src/business/errors/illegal-argument-error.ts, src/data/schema/migration/api/invalid-schema-version-error.ts, src/data/schema/migration/api/schema-base.ts, src/data/schema/migration/api/schema-migration-error.ts, src/data/schema/migration/api/schema-validation-error.ts, src/data/schema/migration/impl/local/local-config-v1-migration.ts, src/data/schema/model/common/application-versions.ts, src/data/schema/model/common/cluster.ts, src/data/schema/model/common/user-identity.ts, src/data/schema/model/local/deployment.ts, src/data/schema/model/local/local-config.ts, test/data/v0.35.1-local-config.yaml, test/unit/data/model/local/local-config.test.ts
* Fixes the `package.json` version to match the currently published `v0.35.1` release
* Adds a completed migration implementation for `LocalConfig`
* Refactors the `soloVersion` field in `LocalConfig`
* Partially Addresses #1463
=> feat: adds migration and full schema support for the local config

docs/contributing/onboarding_questions.md
* fix minor typos in documentation
* Closes #
=> chore: fix minor typos in documentation

version.ts
* update HEDERA_PLATFORM_VERSION to v0.59.5
* Closes #
=> chore: update HEDERA_PLATFORM_VERSION to v0.59.5

src/commands/deployment.ts, src/commands/init.ts, src/core/config/local-config.ts, src/core/config/remote/remote-config-manager.ts, src/core/config/remote/remote-config-validator.ts, test/data/local-config.yaml, test/e2e/commands/dual-cluster-full.test.ts
* extend functionality in the dual cluster full e2e test
* relates to #1642 
* relates to https://github.com/hashgraph/solo/issues/1670
=> chore: extend functionality in the dual cluster full e2e test

.github/pull_request_template.md
* add pull request checklist and commit message documentation
* Closes #1168
=> chore: add pull request checklist and commit message documentation

src/commands/node/handlers.ts, version.ts
=> ci: increase solo-chart version

docs/contributing/onboarding_questions.md, docs/design/archive/multi_user_cluster_support.md, docs/design/archive/solo_reusability_for_dab_tests.md, docs/site/content/User/SDK.md, docs/site/content/User/TaskTool.md, docs/workshops/devcon_2024_fall_workshop.md, examples/address-book/README.md, examples/sdk-network-connection/README.md
* removed codacy issues for http links in markdown files, which address 20x Codacy `MD034 - Bare URL used` issues
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have …
=> chore: removed codacy issues for http links in markdown files

docs/design/archive/multi_user_cluster_support.md, docs/workshops/devcon_2024_fall_workshop.md
* fix Codacy warnings about using tabs instead of spaces in markdown files
* \[ ] This PR added unit …
=> chore: fix Codacy warnings about using tabs instead of spaces in markdown files

.github/workflows/flow-gcs-test.yaml
**Description**:
Update workflow to use commit sha in action
**Related Issue(s)**:
Fixes #1694
=> ci: update workflow to use commit sha in action

.github/pull_request_template.md
* update pull request template to move up related issues section
* \[ ] …
=> chore: update pull request template to move up related issues section

resources/mirror-node-values.yaml, version.ts
* update mirror node version to v0.126.0
* removed mirror node values file `global.image.tag=main` override
N/A
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been …
=> chore: update mirror node version to v0.126.0

src/commands/flags.ts, src/commands/node/tasks.ts, src/core/genesis-network-models/genesis-network-data-constructor.ts
* Fix array size of adminKey when the flag is not set
* Closes #1726
* Closes #1729 
* \[ ] This PR …
=> fix: array size of adminKey when the flag is not set

version.ts
* TBD
* Closes #
* Related to # …
=> chore: bump solo charts to version 0.47.0

examples/create-topic.js
* fix create topic test by checking what key is used
* throw error if create topic test failed, so the test flow can be interrupted.
* Closes #1734 
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit …
=> fix: create topic test

.github/workflows/zxc-update-readme.yaml, README.md
* Fix get start link
* Closes #1723 …
=> fix: doc start link

eslint.config.mjs
* update ESLint configuration to enforce explicit return types and typedef rules
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been …
=> refactor: update ESLint configuration to enforce explicit return types and typedef rules

test/e2e/commands/dual-cluster-full.test.ts
* increase timeout for dual-cluster full test and enable `solo node start` test
* Closes #
* Related to #1642 
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been …
=> test: increase timeout for dual-cluster full test and enable `solo node start` test

docs/site/Taskfile.yaml, eslint.config.mjs, lint-formatter.ts, package-lock.json, package.json, tsconfig.json
* add unicorn eslint rule to enforce lowercase + kabab style `*.ts` file names
* added unicorn recommended eslint rules as warnings
* restructured `eslint.config.mjs` to be more readable
* added lint formatter to provide counts of rule violations and group files by rule violation
* Closes #
* Related to #
* \[x] All changes in …
=> chore: add eslint rule to enforce lowercase kabab `*.ts` file names and added unicorn recommended eslint rules as warnings

resources/extract-platform.sh, version.ts
* add fix for m4 chips running java21
* Closes #
* Related to #
* \[ ] …
=> feat: add fix for m4 chips running java21

eslint.config.mjs, package-lock.json, package.json, src/commands/account.ts, src/commands/flags.ts, src/core/config/local/local-config-data-wrapper.ts, src/core/config/remote/remote-config-manager.ts, src/core/helpers.ts, src/core/key-manager.ts, src/data/schema/migration/api/schema-base.ts, src/data/schema/migration/impl/local/local-config-v1-migration.ts, src/index.ts, src/integration/kube/errors/kube-api-error.ts, src/integration/kube/k8-client/resources/container/k8-client-container.ts, test/helpers/argv-wrapper.ts
* remove eslint warnings for rules: 
* `unicorn/prefer-at`, 
* `unicorn/no-useless-spread`, 
* `unicorn/prefer-structured-clone`
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the …
=> refactor: remove eslint warnings for rules: `unicorn/prefer-at`, `unicorn/no-useless-spread`, `unicorn/prefer-structured-clone`

src/integration/helm/execution/helm-execution-builder.ts
* Change helm executable to correct path
* Closes #1753 
* Related to # …
=> fix: set helm client path with correct installation path

eslint.config.mjs, src/commands/explorer.ts, src/commands/flags.ts, src/commands/network.ts, src/commands/node/handlers.ts, src/commands/node/tasks.ts, src/core/account-manager.ts, src/core/config-manager.ts, src/core/config/remote/components-data-wrapper.ts, src/core/constants.ts, src/core/templates.ts, src/data/backend/impl/environment-storage-backend.ts, src/data/backend/impl/file-storage-backend.ts, src/data/configuration/impl/layered-config.ts, src/data/mapper/impl/flat-key-mapper.ts, src/data/schema/model/utils/transformations.ts, test/e2e/commands/account.test.ts, test/e2e/commands/dual-cluster-full.test.ts, test/e2e/commands/mirror-node.test.ts, test/e2e/integration/core/helm/helm-client.test.ts, test/unit/data/schema/model/remote/remote-config.test.ts
* removed 'unicorn/switch-case-braces' and 'unicorn/numeric-separators-style' rule violations
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below …
=> refactor: removed 'unicorn/switch-case-braces' and 'unicorn/numeric-separators-style' rule violations

.github/workflows/script/update_md.sh, .github/workflows/zxc-update-readme.yaml, docs/site/content/User/StepByStepGuide.md, docs/site/content/User/StepByStepGuide.md.template
* Update markdown documentation generation with more solo commands, espeically destroy commands
* Add a table content
* Update workflow so we can trigger manually from Action web page
* Closes #1761
* \[x] When this PR merges the commits will be squashed and the …
=> chore: update markdown generation

.github/workflows/zxc-code-analysis.yaml, .github/workflows/zxc-unit-test.yaml
Replaces EnricoMi/publish-unit-test-result-action with step-security maintained version
* Closes #1788  …
=> ci: replace action with step-security maintained version

docs/site/content/User/SDK.md, docs/site/content/User/TaskTool.md, examples/Taskfile.examples.yml, examples/Taskfile.yml
* Fix disappeared `task default-with-mirror` command
* Fix explore deploy on 2nd deployment
* update marddown document
N/A
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below …
=> fix: task with mirror

docs/site/content/Developer/DesignDocs/_index.md, docs/site/content/Developer/Development/TaskTool.md, docs/site/content/Developer/Development/_index.md, docs/site/content/Developer/_index.md, docs/site/content/User/GetStarted.md, docs/site/content/User/SoloCommands.md, docs/site/content/User/SoloWithMirrorNode.md, docs/site/data/menu/main.yml
* move TaskTool.md under `Developer/Development`
* updated page Titles for stubs used to auto collapse menus
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message …
=> docs: move TaskTool.md under `Developer/Development`

src/commands/cluster/tasks.ts, src/commands/node/tasks.ts, src/core/account-manager.ts, src/core/config-manager.ts, src/core/config/local/local-config-data-wrapper.ts, src/core/dependency-managers/dependency-manager.ts, src/core/dependency-managers/helm-dependency-manager.ts, src/core/help-renderer.ts, src/core/helpers.ts, src/core/lock/interval-lock-renewal.ts, src/core/lock/interval-lock.ts, src/core/profile-manager.ts, src/data/configuration/impl/layered-config-source.ts, src/data/key/lexer/forest.ts, src/data/key/lexer/lexer-internal-node.ts, src/data/key/lexer/lexer.ts, src/integration/helm/execution/helm-execution-builder.ts, src/integration/helm/execution/helm-execution.ts, src/integration/helm/model/version.ts, src/integration/kube/k8-client/resources/config-map/k8-client-config-maps.ts, src/integration/kube/k8-client/resources/container/k8-client-container.ts, src/integration/kube/k8-client/resources/secret/k8-client-secrets.ts, test/e2e/integration/core/helm/helm-client.test.ts, test/test-add.ts, test/unit/core/helm/software/helm-software-loader.test.ts, test/unit/data/backend/impl/file-storage-backend.test.ts, test/unit/fixtures/simple-object-storage-backend.fixture.ts, version.ts
* issues that `eslint . --fix` auto fixes
* Closes #
* Related to #
* …
=> refactor: eslint --fix

README.md, docs/site/content/User/GetStarted.md
* update GetStarted.md and README.md for improved user guidance
* Closes #
* Related to #
* \[ ] This …
=> docs: update GetStarted.md and README.md for improved user guidance

.github/workflows/flow-hugo-publish.yaml
* disable publish main branch changes to github page
* Closes #
* Related to # …
=> chore: disable publish main branch changes to github page

.github/workflows/flow-hugo-publish.yaml, docs/hugo.toml
* Updates the Hugo base URL
* Minor enhancements to the documentation publish workflow
* Closes #1815  …
=> fix: update docs site for the hiero organization

docs/Taskfile.yaml
* Updates taskfile for proper Hugo publishing
* Closes #1815
* \[ ] …
=> chore: update taskfile for hugo publishing

.github/workflows/script/gcs_test.sh, .github/workflows/script/solo_smoke_test.sh, examples/create-topic.js, examples/external-database-test/Taskfile.yml, src/commands/flags.ts, src/commands/mirror-node.ts, src/commands/network.ts, version.ts
* update javascript test with subscription to topic to test mirror node grpc function
* add new flags for storage, will be used to support AWS
* Closes #1827
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, …
=> feat: add grpc topic test and new flags to support AWS

src/core/config/remote/components/consensus-node-component.ts, src/core/config/remote/components/relay-component.ts, src/core/errors/solo-error.ts, src/core/genesis-network-models/genesis-network-node-data-wrapper.ts, src/core/genesis-network-models/genesis-network-roster-entry-data-wrapper.ts, src/core/model/solo-service.ts, src/core/process-output.ts, src/data/key/config-key-error.ts, src/data/schema/model/utils/transformation-error.ts, src/integration/helm/base/api/version/invalid-semantic-version-exception.ts, src/integration/helm/helm-configuration-exception.ts, src/integration/helm/helm-execution-exception.ts, tsconfig.json
* Enabled the rule `noImplicitOverride` in the `tsconfig`
* Added override to all places to resolve the errors 
* Closes # https://github.com/hashgraph/solo/issues/1820
=> chore(typescript): enable typescript's "noImplicitOverride" and fix all errors

src/commands/block-node.ts, src/commands/network.ts, src/commands/node/tasks.ts, src/core/block-nodes-json-wrapper.ts, src/core/certificate-manager.ts, src/core/config/remote/components-data-wrapper.ts, src/core/constants.ts, src/core/helpers.ts, src/core/templates.ts, test/e2e/commands/block-node.test.ts, test/e2e/commands/network.test.ts, test/e2e/commands/separate-node-add.test.ts, test/helpers/command-invoker.ts, test/test-add.ts, test/test-utility.ts, test/unit/commands/network.test.ts
* Adds logic that creates the `block-nodes.json` if there is active block node in the solo deployment
* Add new class `BlockNodesJsonWrapper` for creating the `block-nodes.json`
* Fixes EsLint warnings inside the `commands/network.ts` 
* Closes #1757
* \[x] This PR added tests (unit, integration, and/or end-to-end)
* \[x] When …
=> feat(block-node): update solo network deploy to create the 'block-nodes.json'

src/core/genesis-network-models/genesis-network-data-wrapper.ts, src/core/genesis-network-models/genesis-network-node-data-wrapper.ts, src/core/helpers.ts, src/types/index.ts, test/e2e/commands/dual-cluster-full.test.ts, test/unit/core/helpers.test.ts, version.ts
* change service endpoints from byte array to base64 string for creating `genesis-network.json` file
* fix some warnings
* enhanced `dual-cluster-full.test.ts` to be able to use a local build path version if environment variables are set
* Closes #
* Related to #
* …
=> fix: change service endpoints from byte array to base64 string for creating genesis network json file

resources/support-zip.sh
* include symbolic link file in downloading node logs
* Closes #1858
* Related to #
* \[ ] This PR …
=> fix: include symbolic link file in downloading node logs

.github/workflows/flow-gcs-test.yaml
* always delete cloud storage bucket
N/A …
=> chore: always delete cloud storage bucket

test/e2e/commands/node-delete.test.ts, test/e2e/commands/node-local-hedera.test.ts, test/e2e/commands/node-update.test.ts, test/e2e/commands/node-upgrade.test.ts, test/e2e/commands/relay.test.ts, test/e2e/end-to-end-node-utility.ts, test/test-add.ts, version-test.ts, version.ts
This PR updates the default network node version to 0.61.4 and adds non-zero values for different e2e test suites:
| **Case** | **Realm** | **Shard** | **E2E Test Suite**     |
|----------|-----------|-----------|------------------------|
| Case 1   | 0         | 0         | Node Add              |
| Case 2   | 1         | 1         | Node Update           |
| Case 3   | 0         | 1         | Node Upgrade          |
| Case 4   | 1         | 0         | Relay                 |
| Case 5   | 65535     | 0         | Node Delete           |
| Case 6   | 0         | 1023      | Node Local Hedera     |
| Case 7   | 65535     | 1023      | Node PEM Stop         |
* Depends on #1783
* Closes #1841
* \[ ] This PR updated …
=> feat: add e2e tests for non zero realm deployments

docs/site/content/User/FAQ.md, src/core/chart-manager.ts, src/integration/helm/helm-client.ts, src/integration/helm/impl/default-helm-client.ts, src/integration/helm/model/add/add-repo-options-builder.ts, src/integration/helm/model/add/add-repo-options.ts, src/integration/helm/request/repository/repository-add-request.ts, test/e2e/integration/core/helm/helm-client.test.ts, test/unit/core/helm/model/add-repo-options-builder.test.ts, test/unit/core/helm/model/repository-add-request.test.ts
* add force-update option to helm repo add request to allow force update helm chart
* update document of how to handle repository already exist error
* Closes #1882 
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit …
=> feat: add force-update option to helm repo add request

README.md, docs/contributing/onboarding_questions.md, docs/design/archive/solo_reusability_for_dab_tests.md, docs/site/content/Developer/Development/TaskTool.md, docs/site/content/_index.md, docs/workshops/devcon_2024_fall_workshop.md, examples/sdk-network-connection/README.md, examples/solo-gke-test/relay-values.yaml, package.json, solo-compose/setup-runner.sh, src/commands/flags.ts, test/unit/data/schema/model/local/local-config.test.ts
* replace hashgraph with hiero in links that we previously missed
* update project version to v0.36.0 and add new configuration files
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, …
=> chore: replace hashgraph with hiero in links that we previously missed, bump solo version to v0.36.0 in package.json

package-lock.json, test/e2e/commands/dual-cluster-full.test.ts
* update `dual-cluster-full.test.ts` to always run the address book check instead of conditionally
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' …
=> chore: update `dual-cluster-full.test.ts` to always run the address book check instead of conditionally

docs/site/content/User/FAQ.md, docs/site/content/User/SoloCommands.md, docs/site/content/User/StepByStepGuide.md, docs/site/content/User/StepByStepGuide.md.template
* run format
* update step by step guide template
* run job to update step by step guide, and commit updates
* run job to update solo command doc, and commit updates
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will …
=> chore: Step by step guide updates

.github/workflows/script/update_md.sh, src/core/error-handler.ts
* solo should exit with non-zero code when exception is thrown
* Closes #1945
* \[ ] This PR added unit …
=> fix: solo should exit with non-zero code when exception is thrown

.github/CODEOWNERS, .github/workflows/flow-deploy-release-artifact.yaml, .github/workflows/flow-gcs-test.yaml, .github/workflows/flow-hugo-publish.yaml, .github/workflows/flow-pull-request-formatting.yaml, .github/workflows/flow-task-test.yaml, .github/workflows/templates/template.zxc-code-analysis.yaml, .github/workflows/templates/template.zxc-env-vars.yaml, .github/workflows/zxc-code-analysis.yaml, .github/workflows/zxc-code-style.yaml, .github/workflows/zxc-e2e-test.yaml, .github/workflows/zxc-env-vars.yaml, .github/workflows/zxc-unit-test.yaml, .github/workflows/zxc-update-readme.yaml
in order to patch `release/0.35` we need the hiero changes to the pipeline
* added Hiero support for `release/0.35`
* Closes #
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit …
=> chore: Hiero support for `release/0.35` 

docs/design/architecture/system/data_layer_architecture.md
* update data layer architecture DeploymentConfig constant name for clarity
* Closes #
* Related to #
* …
=> docs: update data layer architecture DeploymentConfig constant name for clarity

package-lock.json, package.json
This pull request includes a minor change to the `package.json` file. The `postinstall` script has been replaced with a `prepare` script, which runs the `c8-nyc-bridge.mjs` file.
* Closes #1996
* \[x] When this PR merges the commits will be squashed and the title will be used as the commit message, the …
=> fix: resolve post install failure due to c8

.github/workflows/flow-hugo-publish.yaml, docs/Taskfile.yaml, docs/content/User/StepByStepGuide.md, docs/content/User/StepByStepGuide.md.template, docs/data/menu/main.yml
* test run of hugo publish to gh pages for reverting when needed
* Closes #
* Related to #
* \[ ] This …
=> chore: test run of hugo publish to gh pages for reverting when needed

.github/workflows/flow-deploy-release-artifact.yaml
* upload npm logs as artifacts to determine issue in release deploy
* Closes #
* Related to #2013
* \[ …
=> chore: upload npm logs as artifacts to determine issue in release deploy

.github/workflows/zxc-update-readme.yaml
* upload npm logs as artifacts to determine issue in release deploy
* Closes #
* Related to https://github.com/hiero-ledger/solo/issues/2013
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message …
=> chore: upload npm logs as artifacts to determine issue in release deploy #2015

.github/workflows/script/wrapper_for_update_md.sh
* fix: set --allow-same-version on npm version comand to fix release deploy issue
* Closes #2013
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been …
=> fix: set --allow-same-version on npm version comand to fix release deploy issue

.github/workflows/zxc-update-readme.yaml
This pull request updates the `.github/workflows/zxc-update-readme.yaml` file to i#2013 e security and streamline the workflow by modifying how tokens are handled and removing unnecessary steps.
* Added the `token` input to the `actions/checkout` step to use the `GH_ACCESS_TOKEN` secret securely. (`[.github/workflows/zxc-update-readme.yamlR80](diffhunk://#diff-5029a670d83b13dc7d103eca4031e255d4dd38f14baa397f6ac85910685ba25cR80)`)
* Removed the "Upload Logs" step, which uploaded npm logs, as it is no longer needed. (`[.github/workflows/zxc-update-readme.yamlL118-L123](diffhunk://#diff-5029a670d83b13dc7d103eca4031e255d4dd38f14baa397f6ac85910685ba25cL118-L123)`)
* Removed the `GITHUB_TOKEN` environment variable from the "Commit Changes" step to avoid redundancy, as the token is now passed …
=> fix: lack of permissions when committing to the main branch during release

.github/workflows/flow-deploy-release-artifact.yaml
* remove update-readme step from release deployment workflow
* Closes #
* Related to #
* \[ ] This PR …
=> chore: remove update-readme step from release deployment workflow

version.ts
This pull request updates the `SOLO_CHART_VERSION` constant in `version.ts` to reflect the latest version.
* Closes #2038  …
=> fix: update solo charts to v0.53.0 adding PV support for apps and lib folders

version-test.ts, version.ts
* update Hedera platform version to v0.61.7 and test version to v0.60.1
* Closes #
* Related to #
* \[ …
=> fix: update Hedera platform version to v0.61.7 and test version to v0.60.1

.github/workflows/flow-hugo-publish.yaml, .github/workflows/zxc-hugo-publish.yaml
This pull request includes updates to the GitHub Actions workflows related to Hugo builds and publishing. The changes aim to improve naming conventions for clarity and refine conditional logic for better handling of `dry-run` scenarios.
* Updated job names in `.github/workflows/flow-hugo-publish.yaml` to be more descriptive:
- Changed `hugo-docs-build-main` to `Hugo Docs Build - Main`.
- Changed `hugo-docs-build-main-only` to `Hugo Docs Build - Main Only`.
- Changed `hugo-docs-publish-main-only` to `Hugo Docs Publish - Main Only`.
* Modified `if` conditions in `.github/workflows/zxc-hugo-publish.yaml` to simplify and ensure proper handling of `dry-run-enabled`:
- Replaced `inputs.dry-run-enabled != 'true'` with `!inputs.dry-run-enabled` for …
=> chore: update Hugo workflow names for clarity and improve dry run condition handling

.mocharc.yaml
* enable sorting in Mocha configuration for improved test consistency
* Closes #
* Related to #
* \[ ] …
=> chore: enable sorting in Mocha configuration for improved test consistency

src/core/constants.ts
This PR fixes an issue where the error message was overwriting the failed task title.
* Closes #
* Related to # …
=> fix: display title of failed task

src/commands/node/configs.ts, src/core/constants.ts
*check upgrade package before proceed
* Closes #2151
* \[ ] This PR …
=> fix: check upgrade package before perform upgrade

src/commands/cluster/tasks.ts
* Fixed some incorrect logic reported by user
* Related to #2165
* \[ ] …
=> fix: incorrect logic

src/commands/node/tasks.ts, src/core/helpers.ts, src/index.ts
* check if node pvc exsits not just check if flag is enabled
* Closes #2182
* \[ ] This PR added unit …
=> fix: check if node pvc exsits

.github/workflows/flow-gcs-test.yaml, .github/workflows/flow-migration-test.yaml, .github/workflows/script/gcs_test.sh, .github/workflows/support/e2e-test-matrix.json, examples/Taskfile.examples.yml, examples/external-database-test/Taskfile.yml, package-lock.json, version.ts
* update SOLO_CHART_VERSION to 0.54.3 to use solo-cheetah instead of mirror.py for uploading files to the cloud from consensus node
* pass bucket configuration values as string to handle scenario where bucket prefix could be a number (as it is used in gcs_test)
This pull request includes updates to workflows, scripts, configuration files, and versioning. The changes focus on improving error handling, adding new test matrix configurations, updating endpoint URLs, modifying deployment commands, and bumping version numbers for dependencies.
* [`.github/workflows/flow-gcs-test.yaml`](diffhunk://#diff-ace6fa1c3b0eccf534e8f0a7b9c6da5458d0ba2ca6ced6fd1ab78e7992f4e7e1L128-R141): Enhanced error handling for the GCS test script by capturing exit codes, …
=> fix: update SOLO_CHART_VERSION to 0.54.3 to use solo-cheetah

.github/workflows/flow-hugo-publish.yaml
This pull request updates the conditional logic for the `hugo-docs-publish` job in the `.github/workflows/flow-hugo-publish.yaml` file to include an additional dependency on the `setup` job's output.
* [`.github/workflows/flow-hugo-publish.yaml`](diffhunk://#diff-d5ec53944df3276238a84b403bcc823827d7b0bd6bc5ee2fb56c629a66555752L170-R172): Modified the `if` condition for the `hugo-docs-publish` job to check the `needs.setup.outputs.versioned-release` value, ensuring the job only runs when the `setup` job outputs `versioned-release == 'true'`. This adds a dependency on the setup job's output while maintaining existing conditions.
* Closes #
* Related to #
* \[ ] This PR updated …
=> chore: update condition for Hugo docs publish to include versioned release check

.codacy.yaml
This pull request updates the `.codacy.yaml` configuration file to streamline ESLint engine settings and ensure the proper version is enabled.
Configuration updates:
* [`.codacy.yaml`](diffhunk://#diff-c5a5c4ae84ac2b668f86b7aa44844393495c110e6da20e897455bedb8e900c7eR5-R13): Disabled redundant `eslint` and `eslint-8` engines, ensuring only `eslint-9` is enabled with the specified configuration file (`eslint.config.mjs`).
* Closes #
* Related to #
* \[ ] Any `package.json` …
=> chore: update codacy configuration file

.github/workflows/flow-pull-request-checks.yaml, resources/templates/application.properties
* current workflow did not work even skip unit test flag is set true
=> fix: pr checks skip unit test 

docs/site/content/en/templates/step-by-step-guide.template.md
Update docs to have the correct command
* updates the getting started docs to have the correct command for mirror node rest API port forwarding 
* Closes #2255 
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the …
=> docs: update step-by-step-guide.template.md

docs/site/content/en/templates/step-by-step-guide.template.md
* TBD
* Closes #2056
* Related to # …
=> docs: add documentation for node update/add/delete

src/commands/init/init.ts, src/core/constants.ts, src/core/dependency-injection/container-init.ts, src/core/dependency-injection/inject-tokens.ts, src/core/dependency-managers/dependency-manager.ts, src/core/dependency-managers/index.ts, src/core/dependency-managers/kind-dependency-manager.ts, src/core/package-downloader.ts, src/core/templates.ts, test/e2e/integration/core/dependency-managers/helm-dependency-manager.test.ts, test/e2e/integration/core/dependency-managers/kind-dependency-manager.test.ts, test/e2e/integration/core/remote-config-validator.test.ts, version.ts
* TBD
* Closes #2244 
* Related to # …
=> feat: add KindDependencyManager

docs/site/content/en/docs/jvm-debugger.md, docs/site/content/en/docs/solo-with-mirror-node.md, docs/site/content/en/templates/step-by-step-guide.template.md
* update node logs documentation
* Closes #2301
* Related to #
* \[ ] …
=> chore: update node logs documentation

.github/workflows/zxc-e2e-test.yaml
* User can already kick of E2E test with action dashboard or command `gh`
* Update workflow to skip report
* Closes #1962
https://github.com/hiero-ledger/solo/actions/runs/16407947959/job/46357014752
* \[ ] When this PR merges the commits will be squashed and the …
=> feat: manual kick off e2e test

src/commands/quick-start/default-quick-start.ts
This pull request includes a minor enhancement to the `DefaultQuickStartCommand` class. The change ensures that the logger displays a message group after providing instructions for deleting deployed resources.
* Closes #2341 
* Related to #
* \[ ] When this PR …
=> fix: add message group display in quick-start guide

test/e2e/commands/account.test.ts
* Utilize account test to add envoy proxy endpoint test, make sure transaction can go through 
* Closes #2309
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' …
=> chore: add test of envoy proxy endpoint

src/commands/node/configs.ts
* handle optional adminKey flag safely in context configuration
* Closes #2363 
* Related to #
* \[ ] …
=> fix: handle optional adminKey flag safely in context configuration

src/commands/node/tasks.ts
* update post freeze CN source directory for application.properties
* Closes #2395 
* Related to #
* \[ …
=> fix: update post freeze CN source directory for application.properties

.github/workflows/flow-migration-test.yaml
* Remove node logs since network already destroyed in script launch_network.sh
* Closes #2399
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been …
=> fix: remove unnecessary node logs from migration test workflow

.github/workflows/script/solo_smoke_test.sh, src/commands/flags.ts
* do not assign mask value to default value for data sensitive flags
* Closes #2394
* Related to #
* \[ …
=> fix: do not assign mask value to default value for data sensitive flags

Taskfile.yml, src/core/dependency-managers/helm-dependency-manager.ts, src/core/errors/solo-error.ts, src/core/util/arithmetic-error.ts, test/e2e/integration/core/dependency-managers/helm-dependency-manager.test.ts, test/e2e/integration/core/kind/kind-client.test.ts, test/unit/core/kind/execution/kind-execution.test.ts
Add's `set -o pipefail` to `task check`, which solves the issue
Fixes all the linter errors
* Closes # https://github.com/hiero-ledger/solo/issues/2425
* Related to #
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' …
=> chore(lint): fix lint formatting task and the linter errors

.github/workflows/flow-build-application.yaml
* increase build application workflow matrix max parallel from 3 to 5
* Closes #
* Related to #
* \[ ] …
=> chore: increase build application workflow matrix max parallel from 3 to 5

.github/workflows/flow-gcs-test.yaml, .github/workflows/script/gcs_test.sh, src/commands/command-definitions/consensus-command-definition.ts, src/integration/helm/execution/helm-execution.ts
* Add some logic help to debug issue 2568
* could not locally reproduce the error `context "mirror" does not exist`
* also could not reproduce on a branch
* Related to #2568
* \[ ] When this PR merges the commits will be squashed and the title will be used as the …
=> feat: add debug logic

resources/mirror-node-values.yaml, src/commands/mirror-node.ts
* With helm, any command line flag "--set" would override properties defined in value files. Even the "--values" the flag is after "--set" command
* We need to remove hardcode tps in source code, and allow user to use value file to set new tps value
* Closes #2560
* Related to #
* \[ ] All changes in this PR are included in …
=> fix: remove hardcoded pinger tps

.github/dependabot.yml
This pull request updates the Dependabot configuration to group dependency updates and standardize pull request limits across ecosystems. The main focus is to streamline dependency management by grouping related updates and reducing the number of open pull requests.
Dependabot configuration improvements:
* Added `groups` for both `github-actions` and `npm` dependencies, ensuring that all related updates are bundled together for easier review (`.github/dependabot.yml`).
* Reduced the `open-pull-requests-limit` for `npm` from 15 to 5, aligning it with the limit for `github-actions` to prevent overwhelming the review process (`.github/dependabot.yml`).
* Closes #
* Related to #
* \[ ] This …
=> chore(deps): update dependabot configuration to group dependencies and limit open pull requests

.github/workflows/support/examples-test-matrix.json, examples/version-upgrade-test/README.md, examples/version-upgrade-test/Taskfile.yml, src/commands/block-node.ts, src/commands/relay.ts
* add example to upgrade all component
* Closes #
* Related to #2468
* …
=> feat: add example to upgrade all component

src/commands/cluster/tasks.ts, src/core/constants.ts
* fix hard coded resource file
* Closes #2710
* Related to #
* \[ ] …
=> fix: hard coded resource file

src/business/runtime-state/model/aggregated-metrics.ts, src/business/runtime-state/model/cluster-metrics.ts, src/business/runtime-state/services/metrics-server-impl.ts, test/e2e/commands/one-shot-single.test.ts
* enhance cluster metrics with runtime and transaction count tracking
* Closes #
* Related to #
* \[ ] …
=> chore: enhance cluster metrics with runtime and transaction count tracking
